theory LPAC_CodeExport
  imports
    LPAC_Efficient_Checker_Synthesis
    LLVM_ASCII_String
    IICF_Copying_List
begin

text \<open>This theory defines types for the c interface and also handles importing
  the data generated by the c parser into the target datatypes of the verified
  parser. Note that most functions in here are not verified, so they are part of the
  trusted code base.\<close>

section \<open>A ternary union type\<close>

text \<open>The library only ships the binary union example \<open>ll_sum\<close> (and not in the
  IICF import). The tagged union in \<open>rule\<close> has three members, so we provide a
  ternary union type, modelled on \<open>ll_sum\<close>.\<close>

declare [[llc_compile_union=true]]

datatype ('a,'b,'c) ll_union3 =
    is_U3Zero: U3Zero
  | is_U3a: U3a (the_u3a: 'a)
  | is_U3b: U3b (the_u3b: 'b)
  | is_U3c: U3c (the_u3c: 'c)

instantiation ll_union3 :: (llvm_rep,llvm_rep,llvm_rep) llvm_rep
begin
  fun to_val_ll_union3 :: \<open>('a,'b,'c) ll_union3 \<Rightarrow> llvm_val\<close> where
    "to_val_ll_union3 U3Zero = LL_UNION (UN_ZERO_INIT [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3a x) = LL_UNION (UN_SEL [] (to_val x) [struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3b x) = LL_UNION (UN_SEL [struct_of TYPE('a)] (to_val x) [struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3c x) = LL_UNION (UN_SEL [struct_of TYPE('a), struct_of TYPE('b)] (to_val x) [])"

  fun from_val_ll_union3 :: \<open>llvm_val \<Rightarrow> ('a,'b,'c) ll_union3\<close> where
    "from_val_ll_union3 (LL_UNION (UN_ZERO_INIT _)) = U3Zero"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [] x [_,_])) = U3a (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_] x [_])) = U3b (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_,_] x [])) = U3c (from_val x)"
  | "from_val_ll_union3 _ = undefined"

  definition [simp]: "struct_of_ll_union3 (_::('a,'b,'c) ll_union3 itself) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  definition [simp]: "init_ll_union3 = U3Zero"

  instance
    apply standard
    apply (all \<open>(clarsimp simp: comp_def fun_eq_iff)?\<close>)
    subgoal for x by (cases x) auto
    subgoal for v by (cases v rule: from_val_ll_union3.cases) auto
    subgoal for x by (cases x) auto
    done
end

lemma struct_of_ll_union3[ll_struct_of]:
  "struct_of TYPE(('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  by simp

definition ll_u3_extr_a :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'a llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_a x \<equiv> ll_dest_union x 0\<close>

definition ll_u3_extr_b :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'b llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_b x \<equiv> ll_dest_union x 1\<close>

definition ll_u3_extr_c :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'c llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_c x \<equiv> ll_dest_union x 2\<close>

lemma ll_u3_extr_simps:
  \<open>is_U3a x \<Longrightarrow> ll_u3_extr_a x = Mreturn (the_u3a x)\<close>
  \<open>is_U3b x \<Longrightarrow> ll_u3_extr_b x = Mreturn (the_u3b x)\<close>
  \<open>is_U3c x \<Longrightarrow> ll_u3_extr_c x = Mreturn (the_u3c x)\<close>
  unfolding ll_u3_extr_a_def ll_u3_extr_b_def ll_u3_extr_c_def
  by (cases x; simp add: ll_dest_union_def checked_from_val_def llvm_dest_union_def)+

lemma ll_u3_extr_rules[vcg_rules]:
  \<open>llvm_htriple (\<up>(is_U3a x)) (ll_u3_extr_a x) (\<lambda>r. \<up>(r = the_u3a x))\<close>
  \<open>llvm_htriple (\<up>(is_U3b x)) (ll_u3_extr_b x) (\<lambda>r. \<up>(r = the_u3b x))\<close>
  \<open>llvm_htriple (\<up>(is_U3c x)) (ll_u3_extr_c x) (\<lambda>r. \<up>(r = the_u3c x))\<close>
  supply [vcg_normalize_simps] = ll_u3_extr_simps
  by vcg

section \<open>C Interface Types\<close>

text \<open>We describe the datatypes that will be instantiated by the c parser.\<close>

type_synonym c_slice = \<open>64 word \<times> 8 word ptr\<close>
type_synonym c_term = \<open>64 word \<times> c_slice ptr\<close>
type_synonym c_monomial = \<open>c_slice \<times> 8 word \<times> c_term\<close>
type_synonym c_polynomial = \<open>64 word \<times> c_monomial ptr\<close>

type_synonym c_input = \<open>64 word \<times> c_polynomial\<close>
type_synonym c_inputs = \<open>64 word \<times> c_input ptr\<close>

type_synonym c_summand = \<open>c_polynomial ptr \<times> 64 word\<close>
type_synonym c_summands = \<open>64 word \<times> c_summand ptr\<close>
type_synonym c_lc_rule = \<open>64 word \<times> c_summands \<times> c_polynomial\<close>
type_synonym c_del_rule = \<open>64 word\<close>
type_synonym c_ext_rule = \<open>64 word \<times> c_slice \<times> c_polynomial\<close>
type_synonym c_rule = \<open>32 word \<times> (c_lc_rule, c_del_rule, c_ext_rule) ll_union3\<close>
type_synonym c_proof = \<open>64 word \<times> c_rule ptr\<close>

type_synonym c_target = \<open>c_polynomial\<close>

section \<open>Import functions\<close>

subsection \<open>Generic Array to Open List Conversion\<close>

text \<open>We define a synonym for `id` to indicate Array to list conversion on the HOL level.
  Similarly to how we can use `COPY` on the HOL side to enforce copying of structures.\<close>
definition \<open>ARR2LS = (id :: 'a list \<Rightarrow> 'a list)\<close>

lemma arr2ls_refine: \<open>(\<lambda>x. RETURN x, RETURN o ARR2LS) \<in> Id \<rightarrow>\<^sub>f \<langle>Id\<rangle>nres_rel\<close>
  apply (intro frefI nres_relI)
  unfolding ARR2LS_def
  by auto

definition arr_to_list :: \<open>'a list \<Rightarrow> 'a list nres\<close> where
  \<open>arr_to_list arr = doN{
    ASSERT(length arr < max_snat 64);
    let l = length arr;
    (ls, _) \<leftarrow> WHILEIT
      (\<lambda>(ls, i). i \<le> length arr \<and> ls = drop (l-i) arr)
      (\<lambda>(_, i). i < length arr)
      (\<lambda>(ls, i). doN {
        ASSERT(i < length arr);
        RETURN(arr!(l-i-1) # ls, i+1)
      })
      ([], 0);
    RETURN ls
  }\<close>

lemma arr_to_list_correct:
    shows \<open>(arr_to_list, \<lambda>x. RETURN x) \<in> [\<lambda> arr. length arr < max_snat 64]\<^sub>f Id \<rightarrow> \<langle>Id\<rangle>nres_rel\<close>
  apply (intro frefI nres_relI)
  subgoal for x y
    unfolding arr_to_list_def
    apply (refine_vcg WHILEIT_rule[where R="measure (\<lambda>(_, i). length x - i)"])
    apply clarsimp_all
    subgoal by (metis drop_minus rev_nth)
    subgoal by linarith
    done
  done

lemmas arr_to_list_refine = arr_to_list_correct[FCOMP arr2ls_refine]

context
  fixes A :: \<open>'a \<Rightarrow> 'b::llvm_rep \<Rightarrow> assn\<close>
  assumes PURE: \<open>is_pure A\<close>
  notes [safe_constraint_rules] = PURE
  notes [sepref_frame_free_rules] = mk_free_is_pure[OF PURE]
begin

sepref_definition parr_to_list_impl is \<open>arr_to_list\<close>
  :: \<open>(larray_assn' size_t A)\<^sup>k \<rightarrow>\<^sub>a (cl_assn' A)\<close>
  unfolding arr_to_list_def
  apply (annot_snat_const size_t)
  by sepref

lemmas ARR2LS_hnr =
  parr_to_list_impl.refine[FCOMP arr_to_list_refine]

end

subsection \<open>Generic Array to List Conversion with Owned Elements\<close>

definition is_import
  :: \<open>('a \<Rightarrow> 'b::llvm_rep \<Rightarrow> assn) \<Rightarrow> ('a \<Rightarrow> 'c::llvm_rep \<Rightarrow> assn) \<Rightarrow> ('b \<Rightarrow> 'c llM) \<Rightarrow> bool\<close>
  where \<open>is_import A B impf \<equiv> (impf, RETURN o COPY) \<in> A\<^sup>k \<rightarrow>\<^sub>a B\<close>

lemma is_copy_is_import: \<open>is_copy A cp \<Longrightarrow> is_import A A cp\<close>
  unfolding is_copy_def is_import_def .

lemma is_pure_is_import: \<open>is_pure A \<Longrightarrow> is_import A A Mreturn\<close>
  using is_copy_pure_gen_algo[unfolded CONSTRAINT_def GEN_ALGO_def]
  by (blast intro: is_copy_is_import)

definition wo_nth_import :: \<open>('b::llvm_rep \<Rightarrow> 'c::llvm_rep llM) \<Rightarrow> 'b ptr \<Rightarrow> 64 word \<Rightarrow> 'c llM\<close>
  where [llvm_inline]: \<open>wo_nth_import impf p i \<equiv> doM {
    x \<leftarrow> array_nth p i;
    r \<leftarrow> impf x;
    p \<leftarrow> array_upd p i x;
    Mreturn r
  }\<close>

definition ARR2LS_n :: \<open>nat \<Rightarrow> 'a list \<Rightarrow> 'a list\<close> where
  \<open>ARR2LS_n n xs = xs\<close>

definition arr_to_list_n :: \<open>nat \<Rightarrow> 'a list \<Rightarrow> 'a list nres\<close> where
  \<open>arr_to_list_n n arr = doN {
    ASSERT (n = length arr \<and> n < max_snat 64);
    (ls, _) \<leftarrow> WHILEIT
      (\<lambda>(ls, i). i \<le> n \<and> ls = drop (n - i) arr)
      (\<lambda>(_, i). i < n)
      (\<lambda>(ls, i). doN {
        ASSERT (i < n \<and> n < max_snat 64);
        x \<leftarrow> mop_list_get arr (n - i - 1);
        RETURN (x # ls, i + 1)
      })
      ([], 0);
    RETURN ls
  }\<close>

lemma arr_to_list_n_le:
  fixes n :: nat and arr :: \<open>'a list\<close>
  assumes \<open>n = length arr\<close> and \<open>n < max_snat 64\<close>
  shows \<open>arr_to_list_n n arr \<le> RETURN arr\<close>
  unfolding arr_to_list_n_def mop_list_get_alt
  apply (refine_vcg WHILEIT_rule[where R=\<open>measure (\<lambda>(_, i). n - i)\<close>])
  using assms
  apply clarsimp_all
  subgoal by (simp add: drop_minus rev_nth)
  subgoal by linarith
  done

lemma arr_to_list_n_correct:
  \<open>(uncurry arr_to_list_n, uncurry (RETURN oo ARR2LS_n))
    \<in> [\<lambda>(n, arr). n = length arr \<and> n < max_snat 64]\<^sub>f Id \<times>\<^sub>r Id \<rightarrow> \<langle>Id\<rangle>nres_rel\<close>
  by (intro frefI nres_relI)
     (auto simp: ARR2LS_n_def intro!: arr_to_list_n_le)

context
  fixes A :: \<open>'a \<Rightarrow> 'b::llvm_rep \<Rightarrow> assn\<close>
    and B :: \<open>'a \<Rightarrow> 'c::llvm_rep \<Rightarrow> assn\<close>
    and impf :: \<open>'b \<Rightarrow> 'c llM\<close>
  assumes IMP: \<open>is_import A B impf\<close>
  notes [safe_constraint_rules] = CN_FALSEI[of is_pure A]
begin

text \<open>NB: \<open>import_rule\<close> and \<open>wo_nth_import_rule\<close> must NOT carry a global
  \<open>[vcg_rules]\<close> attribute: on context exit the attribute is re-applied to the
  exported rule, which is guarded by the (never dischargeable) premise
  \<open>is_import ?A ?B ?impf\<close> and — for \<open>import_rule\<close> — has the fully schematic
  command head \<open>?impf ?c\<close> that HO-unifies with every command. Such a rule makes
  every later \<open>vcg\<close> invocation in the import closure diverge. Supply the rules
  locally in the proofs (inside this context) that need them.\<close>

lemma import_rule: \<open>llvm_htriple (A a c) (impf c) (\<lambda>r. A a c ** B a r)\<close>
  using hfref_htriple_k1[OF IMP[unfolded is_import_def]] by simp

lemma wo_nth_import_rule:
  \<open>llvm_htriple
     (eoarray_assn A (map Some xs) p ** \<upharpoonleft>snat.assn i ii ** \<up>\<^sub>d(i < length xs))
     (wo_nth_import impf p ii)
     (\<lambda>r. eoarray_assn A (map Some xs) p ** B (xs ! i) r)\<close>
  unfolding wo_nth_import_def eoarray_assn_def
  supply [simp] = map_update[symmetric]
  supply [vcg_rules] = import_rule
  by vcg

lemma wo_nth_import_hnr[sepref_fr_rules]:
  \<open>(uncurry (wo_nth_import impf), uncurry mop_list_get)
    \<in> (woarray_assn A)\<^sup>k *\<^sub>a (snat_assn' TYPE(64))\<^sup>k \<rightarrow>\<^sub>a B\<close>
  unfolding snat_rel_def snat.assn_is_rel[symmetric]
  apply sepref_to_hoare
  apply (clarsimp simp: refine_pw_simps mop_list_get_alt woarray_assn_conv)
  supply [vcg_rules] = wo_nth_import_rule
  apply vcg
  done

sepref_definition arr_to_list_import_impl is \<open>uncurry arr_to_list_n\<close>
  :: \<open>(snat_assn' TYPE(size_t))\<^sup>k *\<^sub>a (woarray_assn A)\<^sup>k \<rightarrow>\<^sub>a cl_assn' B\<close>
  unfolding arr_to_list_n_def
  apply (annot_snat_const size_t)
  by sepref

lemmas ARR2LS_n_hnr = arr_to_list_import_impl.refine[FCOMP arr_to_list_n_correct]

end

definition arr_with_len_assn
  :: \<open>('a \<Rightarrow> 'b::llvm_rep \<Rightarrow> assn) \<Rightarrow> 'a list \<Rightarrow> 64 word \<times> 'b ptr \<Rightarrow> assn\<close>
  where \<open>arr_with_len_assn A \<equiv> \<lambda>xs (ni, pi).
    \<upharpoonleft>snat.assn (length xs) ni ** woarray_assn A xs pi\<close>

lemma arr_to_list_import_is_import:
  assumes IMP: \<open>is_import A B impf\<close>
  shows \<open>is_import (arr_with_len_assn A) (cl_assn' B)
           (\<lambda>(ni, pi). arr_to_list_import_impl impf ni pi)\<close>
proof -
  note HT = hfref_htriple_k1_k2_guard[OF ARR2LS_n_hnr[OF IMP]]
  show ?thesis
    unfolding is_import_def
    apply sepref_to_hoare
    apply (clarsimp simp: arr_with_len_assn_def)
    subgoal for xs ni pi
      apply (rule htriple_pure_preI)
      apply (clarsimp dest!: pure_part_split_conj)
      subgoal premises prems
      proof -
        have PRE: \<open>(\<lambda>(n, arr). n = length arr \<and> n < max_snat 64) (length xs, xs)\<close>
          using prems snat_lt_max_snat[of ni] by (auto simp: snat.assn_def)
        show ?thesis
          using HT[OF PRE, of ni pi]
          by (simp add: ARR2LS_n_def pure_app_eq in_snat_rel_conv_assn
            snat.assn_is_rel[symmetric] snat_rel_def sep_algebra_simps)
      qed
      done
    done
qed

subsection \<open>Primitive importers\<close>

definition slice_to_str :: \<open>char list \<Rightarrow> char list\<close>
  where \<open>slice_to_str \<equiv> ARR2LS\<close>

lemmas stra_ARR2LS_hnr = ARR2LS_hnr[OF char_assn_pure]

lemmas parr_to_list_impl_char_code [llvm_inline] =
  parr_to_list_impl_def[OF char_assn_pure]

text \<open>Note that `c_slice = \<open>64 word \<times> 8 word ptr\<close>`, i.e. `c_slice` is a list of characters.
  In particular, `c_slice` is a refinment target given by `stra_assn`.\<close>
sepref_def slice_to_str_impl is \<open>RETURN o slice_to_str\<close>
  :: \<open>stra_assn\<^sup>k \<rightarrow>\<^sub>a strl_assn'\<close>
  unfolding slice_to_str_def 
  supply [sepref_fr_rules] = stra_ARR2LS_hnr
  by sepref

subsubsection \<open>The constant 0 at \<open>sbi_assn\<close>\<close>

definition int0 :: int where \<open>int0 \<equiv> 0\<close>

definition signed_big_int0 :: signed_big_int where
  \<open>signed_big_int0 \<equiv> ([], False)\<close>

lemma signed_big_int0_\<alpha>: \<open>signed_big_int_to_int ([], False) = 0\<close>
  by eval

lemma signed_big_int0_refine: \<open>(signed_big_int0, int0) \<in> signed_big_int_rel\<close>
  by (auto simp: signed_big_int0_def int0_def signed_big_int_rel_def in_br_conv
      signed_big_int0_\<alpha> signed_big_int_invar_def big_int_invar_def \<sigma>_def limbs_of_def)

lemma signed_big_int0_alt: \<open>signed_big_int0 = (op_al_empty TYPE(size_t), False)\<close>
  by (simp add: signed_big_int0_def)

sepref_def signed_big_int0_impl is \<open>uncurry0 (RETURN signed_big_int0)\<close>
  :: \<open>unit_assn\<^sup>k \<rightarrow>\<^sub>a sbi_aux_assn\<close>
  unfolding signed_big_int0_alt
  by sepref

sepref_register int0

context notes [fcomp_norm_unfold] = sbi_assn_def[symmetric] begin
lemmas signed_big_int0_hnr[sepref_fr_rules] =
  signed_big_int0_impl.refine[FCOMP signed_big_int0_refine]
end

subsubsection \<open>Number-string checker\<close>

lemma foldl_conj_conv: \<open>foldl (\<lambda>acc d. acc \<and> P d) b xs \<longleftrightarrow> b \<and> (\<forall>x\<in>set xs. P x)\<close>
  by (induction xs arbitrary: b) auto

lemma is_ascii_unum_str_conv:
  \<open>is_ascii_unum_str ss \<longleftrightarrow> ss \<noteq> [] \<and> (\<forall>c\<in>set ss. is_ascii_unum c)\<close>
  unfolding is_ascii_unum_str_def foldl_conj_conv
  by presburger

lemma is_ascii_unum_char_conv:
  \<open>is_ascii_unum c \<longleftrightarrow> op_char_48 \<le> c \<and> c \<le> op_char_57\<close>
  unfolding is_ascii_unum_def less_eq_char_inst less_eq_char_def by simp

lemma ascii_hyphen_char_conv: \<open>ascii_hyphen = op_char_45\<close>
  unfolding ascii_hyphen_def by simp

lemma hyphen_not_unum: \<open>\<not> is_ascii_unum op_char_45\<close>
  unfolding is_ascii_unum_def by simp

lemma all_nth_shift_conv:
  \<open>(\<forall>k. k < n - 1 \<longrightarrow> P (Suc k)) \<longleftrightarrow> (\<forall>j. 1 \<le> j \<and> j < (n::nat) \<longrightarrow> P j)\<close>
  apply (rule iffI; clarsimp)
  subgoal for j by (drule spec[of _ \<open>j - 1\<close>]) auto
  done

lemma is_ascii_snum_str_idx_conv:
  assumes \<open>s \<noteq> []\<close>
  shows \<open>is_ascii_snum_str s \<longleftrightarrow>
    (if s ! 0 = op_char_45 then 1 else 0) < length s \<and>
    (\<forall>j. (if s ! 0 = op_char_45 then 1 else 0) \<le> j \<and> j < length s \<longrightarrow>
       is_ascii_unum (s ! j))\<close>
proof (cases \<open>s ! 0 = op_char_45\<close>)
  case True
  have unum_tl: \<open>(\<forall>c\<in>set (tl s). is_ascii_unum c) \<longleftrightarrow>
      (\<forall>j. 1 \<le> j \<and> j < length s \<longrightarrow> is_ascii_unum (s ! j))\<close>
    using assms
    by (metis Cons_nth_drop_Suc One_nat_def drop0 in_set_drop_conv_nth
    length_greater_0_conv list.sel(3))
  have \<open>\<not> is_ascii_unum_str s\<close>
    using True assms hyphen_not_unum nth_mem[of 0 s]
    unfolding is_ascii_unum_str_conv
    by (metis hyphen_not_unum assms True length_greater_0_conv)
  then show ?thesis
    using True assms
    unfolding is_ascii_snum_str_def is_ascii_unum_str_conv ascii_hyphen_char_conv
      is_ascii_unum_def op_char_45_def
    apply (simp add: hd_conv_nth unum_tl)
    by (smt (verit) Cons_nth_drop_Suc Nitpick.size_list_simp(2) drop0 drop_all
    in_set_drop_conv_nth le_eq_less_or_eq list.sel(3) nat_neq_iff)
next
  case False
  then show ?thesis
    using assms
    unfolding is_ascii_snum_str_def is_ascii_unum_str_conv ascii_hyphen_char_conv
      is_ascii_unum_def op_char_45_def
    by (simp add: hd_conv_nth all_set_conv_all_nth)
qed

definition is_snum_check :: \<open>char list \<Rightarrow> bool nres\<close> where
  \<open>is_snum_check s = doN {
    ASSERT (length s < max_snat 64);
    let n = length s;
    if n = 0 then RETURN False
    else doN {
      c \<leftarrow> mop_list_get s 0;
      let start = (if c = op_char_45 then 1 else 0);
      if n \<le> start then RETURN False
      else doN {
        (b, _) \<leftarrow> WHILEIT
          (\<lambda>(b, i). start \<le> i \<and> i \<le> n \<and>
             b = (\<forall>j. start \<le> j \<and> j < i \<longrightarrow> is_ascii_unum (s ! j)))
          (\<lambda>(b, i). b \<and> i < n)
          (\<lambda>(b, i). doN {
            ASSERT (i < n);
            c \<leftarrow> mop_list_get s i;
            RETURN (b \<and> (op_char_48 \<le> c \<and> c \<le> op_char_57), i + 1)
          })
          (True, start);
        RETURN b
      }
    }
  }\<close>

lemma is_snum_check_correct:
  assumes \<open>length s < max_snat 64\<close>
  shows \<open>is_snum_check s \<le> SPEC (\<lambda>b. b = is_ascii_snum_str s)\<close>
  unfolding is_snum_check_def mop_list_get_alt
  apply (refine_vcg WHILEIT_rule[where R=\<open>measure (\<lambda>(_, i). length s - i)\<close>])
  subgoal using assms by simp
  subgoal
    using assms apply auto 
    using is_ascii_snum_str_nempty by blast
  subgoal using assms by auto
  subgoal
    using assms apply auto
    by (metis is_ascii_snum_str_idx_conv op_char_45_def
    verit_comp_simplify1(3))
  subgoal using assms by auto
  subgoal using assms by auto
  subgoal using assms by auto
  subgoal using Legacy_Aliases.le_def by blast
  subgoal using Legacy_Aliases.le_def by blast
  subgoal by (metis old.prod.case pre_list_get_def)
  subgoal
    by (metis (mono_tags, opaque_lifting) Suc_eq_plus1 less_numeral_extra(3)
    nat_geq_1_eq_neqz prod.inject zero_less_Suc zero_order(1))
  subgoal using HM.rewr_kp1len by blast
  subgoal by (auto simp: is_ascii_unum_char_conv less_Suc_eq)
  subgoal using assms by auto
  subgoal by (auto simp: Legacy_Aliases.le_def is_ascii_snum_str_idx_conv)
  done

sepref_register is_snum_check
sepref_def is_snum_check_impl is \<open>is_snum_check\<close>
  :: \<open>stra_assn\<^sup>k \<rightarrow>\<^sub>a bool1_assn\<close>
  unfolding is_snum_check_def
  apply (annot_snat_const size_t)
  by sepref

subsubsection \<open>Checked slice-to-integer conversion\<close>

sepref_register slice_to_str str_sval

definition slice_to_big_int :: \<open>char list \<Rightarrow> bool \<times> int\<close> where
  \<open>slice_to_big_int x =
    (is_ascii_snum_str x, if is_ascii_snum_str x then str_sval x else int0)\<close>

definition slice_to_big_int_m :: \<open>char list \<Rightarrow> (bool \<times> int) nres\<close> where
  \<open>slice_to_big_int_m x = doN {
    ASSERT (length x < max_snat 64);
    b \<leftarrow> is_snum_check x;
    if b then doN {
      s \<leftarrow> RETURN (slice_to_str x);
      ASSERT (is_ascii_snum_str s);
      RETURN (True, str_sval s)
    } else RETURN (False, int0)
  }\<close>

lemma slice_to_big_int_m_le:
  assumes L: \<open>length x < max_snat 64\<close>
  shows \<open>slice_to_big_int_m x \<le> RETURN (slice_to_big_int x)\<close>
proof -
  note C = is_snum_check_correct[OF L]
  show ?thesis
    unfolding slice_to_big_int_m_def slice_to_big_int_def slice_to_str_def ARR2LS_def
    apply (refine_vcg specify_left[OF C])
    using L by auto
qed

lemma slice_to_big_int_m_correct:
  \<open>(slice_to_big_int_m, RETURN o slice_to_big_int)
    \<in> [\<lambda>x. length x < max_snat 64]\<^sub>f Id \<rightarrow> \<langle>Id\<rangle>nres_rel\<close>
  by (intro frefI nres_relI) (auto intro!: slice_to_big_int_m_le)


text \<open>The \<open>str_sval\<close> rule registered in \<open>LLVM_ASCII_String\<close> retains an
  unnormalized \<open>hr_comp strl_assn' (\<langle>Id\<rangle>list_rel)\<close> argument assertion, so
  \<open>sepref\<close> never applies it. Re-derive the collapsed form.\<close>
lemma str_sval_hnr'[sepref_fr_rules]:
  \<open>(str_sval_impl, RETURN o str_sval) \<in> [is_ascii_snum_str]\<^sub>a strl_assn'\<^sup>d \<rightarrow> sbi_assn\<close>
  using str_sval_hnr by simp

sepref_def slice_to_big_int_impl is \<open>slice_to_big_int_m\<close>
  :: \<open>stra_assn\<^sup>k \<rightarrow>\<^sub>a bool1_assn \<times>\<^sub>a sbi_assn\<close>
  unfolding slice_to_big_int_m_def
  by sepref

lemmas slice_to_big_int_hnr =
  slice_to_big_int_impl.refine[FCOMP slice_to_big_int_m_correct]

subsection \<open>Bridges between guarded and unguarded refinement rules\<close>

text \<open>A precondition that is a representation invariant of the argument
  assertion can be dropped from a guarded \<open>hfref\<close> rule.\<close>
lemma hfref_precond_from_assn:
  assumes R: \<open>(f, g) \<in> [P]\<^sub>a A\<^sup>k \<rightarrow> B\<close>
  assumes I: \<open>\<And>a c. pure_part (A a c) \<Longrightarrow> P a\<close>
  shows \<open>(f, g) \<in> A\<^sup>k \<rightarrow>\<^sub>a B\<close>
  apply (rule hfrefI)
  apply (rule hn_refine_preI)
  apply (rule hfrefD[OF R])
  by (auto intro: I pure_partI)

lemma pure_part_EXS: \<open>pure_part (EXS x. F x) \<Longrightarrow> \<exists>x. pure_part (F x)\<close>
  by (auto simp: pure_part_def sep_algebra_simps)

lemma pure_part_hr_comp:
  \<open>pure_part (hr_comp A R a c) \<Longrightarrow> \<exists>b. (b, a) \<in> R \<and> pure_part (A b c)\<close>
  unfolding hr_comp_def
  by (auto dest!: pure_part_EXS pure_part_split_conj)

lemma stra_assn_len_bound: \<open>pure_part (stra_assn s si) \<Longrightarrow> length s < max_snat 64\<close>
proof -
  assume \<open>pure_part (stra_assn s si)\<close>
  then obtain b where R1: \<open>(b, s) \<in> \<langle>the_pure char_assn\<rangle>list_rel\<close>
    and P1: \<open>pure_part (raw_larray_assn b si)\<close>
    unfolding larray_assn_def by (auto dest!: pure_part_hr_comp)
  from P1 obtain nxs where R2: \<open>(nxs, b) \<in> larray1_rel\<close>
    and P2: \<open>pure_part ((snat_assn \<times>\<^sub>a array_assn id_assn) nxs si)\<close>
    unfolding raw_larray_assn_def by (auto dest!: pure_part_hr_comp)
  obtain n xs where NXS: \<open>nxs = (n, xs)\<close> by (cases nxs)
  obtain ni pi where SI: \<open>si = (ni, pi)\<close> by (cases si)
  from P2 have \<open>(ni, n) \<in> snat_rel\<close>
    unfolding NXS SI prod_assn_pair_conv
    by (auto dest!: pure_part_split_conj)
  then have \<open>n < max_snat 64\<close>
    using snat_lt_max_snat[of ni]
    by (auto simp: snat_rel_def snat.rel_def in_br_conv)
  moreover have \<open>n = length b\<close>
    using R2 unfolding NXS by (auto simp: larray1_rel_prenorm)
  moreover have \<open>length b = length s\<close>
    using R1 by (rule list_rel_imp_same_length)
  ultimately show ?thesis by simp
qed

lemma slice_to_big_int_hnr'[sepref_fr_rules]:
  \<open>(slice_to_big_int_impl, RETURN o slice_to_big_int)
    \<in> stra_assn\<^sup>k \<rightarrow>\<^sub>a bool1_assn \<times>\<^sub>a sbi_assn\<close>
  by (rule hfref_precond_from_assn[OF slice_to_big_int_hnr stra_assn_len_bound])

sepref_register slice_to_big_int

lemma hfref_htriple_k0:
  assumes R: \<open>(uncurry0 f, uncurry0 (RETURN g)) \<in> unit_assn\<^sup>k \<rightarrow>\<^sub>a B\<close>
  shows \<open>llvm_htriple \<box> f (\<lambda>r. B g r)\<close>
proof -
  note HNR = R[to_hnr, unfolded autoref_tag_defs]
  note HT = HNR[THEN hn_refineD]
  show ?thesis
    apply (rule htriple_ent_pre[OF _ htriple_ent_post[OF _ HT]])
    unfolding hn_ctxt_def
    subgoal by (auto simp: entails_def sep_algebra_simps pure_def
      pred_lift_extract_simps)
    subgoal by (auto simp: entails_def sep_algebra_simps pred_lift_extract_simps
      sep_conj_exists pw_le_iff refine_pw_simps)
    subgoal by (simp add: refine_pw_simps)
    done
qed

section \<open>Verified Import of the C-Parsed Structures\<close>

text \<open>Methodology: every C-side structure gets a refinement assertion whose
  \<^emph>\<open>abstract\<close> value is the already-parsed HOL value (built by composing raw
  component assertions with a parse function via \<open>hr_comp\<close>/\<open>br\<close>). Every
  importer is then an \<open>is_import\<close> instance, i.e. an abstract \<open>COPY\<close>, and the
  array-shaped levels are instances of the generic
  \<open>arr_to_list_import_is_import\<close>. What remains trusted is only the claim that
  the C parser establishes the source assertions.\<close>

subsection \<open>Import combinators\<close>

text \<open>Bridge from a parse-style program to an \<open>is_import\<close>-style abstract
  \<open>COPY\<close>: composing with this \<open>fref\<close> moves the parse function into the source
  assertion.\<close>
lemma import_parse_fref:
  \<open>(RETURN o f, RETURN o COPY) \<in> br f (\<lambda>_. True) \<rightarrow>\<^sub>f \<langle>Id\<rangle>nres_rel\<close>
  by (intro frefI nres_relI) (auto simp: in_br_conv)

text \<open>Componentwise import of a pair.\<close>
lemma is_import_prod:
  assumes A: \<open>is_import A B f\<close> and A': \<open>is_import A' B' f'\<close>
  shows \<open>is_import (A \<times>\<^sub>a A') (B \<times>\<^sub>a B')
           (\<lambda>(c, c'). doM { b \<leftarrow> f c; b' \<leftarrow> f' c'; Mreturn (b, b') })\<close>
  unfolding is_import_def
  supply [vcg_rules] = hfref_htriple_k1[OF A[unfolded is_import_def]]
    hfref_htriple_k1[OF A'[unfolded is_import_def]]
  apply sepref_to_hoare
  subgoal for x xi
    apply (cases x; cases xi)
    apply (clarsimp simp: refine_pw_simps sep_algebra_simps
      pred_lift_extract_simps sep_conj_exists)
    by vcg
  done

lemma si64_is_import: \<open>is_import si64_assn si64_assn Mreturn\<close>
  by (intro is_pure_is_import) simp

subsection \<open>Terms (variable lists)\<close>

lemma slice_to_str_is_import: \<open>is_import stra_assn strl_assn' slice_to_str_impl\<close>
proof -
  have \<open>slice_to_str = COPY\<close> by (auto simp: slice_to_str_def ARR2LS_def)
  then show ?thesis
    unfolding is_import_def using slice_to_str_impl.refine by simp
qed

definition imp_term :: \<open>c_term \<Rightarrow> monom_conc llM\<close> where [llvm_code]:
  \<open>imp_term \<equiv> \<lambda>(ni, ai). arr_to_list_import_impl slice_to_str_impl ni ai\<close>

lemmas arr_to_list_import_slice_inline[llvm_inline] =
  arr_to_list_import_impl_def[OF slice_to_str_is_import]

lemma imp_term_is_import:
  \<open>is_import (arr_with_len_assn stra_assn) monom_assn imp_term\<close>
  using arr_to_list_import_is_import[OF slice_to_str_is_import]
  unfolding imp_term_def .

text \<open>Named abstract operation for use in downstream syntheses.\<close>
definition import_term :: \<open>char list list \<Rightarrow> char list list\<close> where
  \<open>import_term \<equiv> COPY\<close>

sepref_register import_term

lemma import_term_hnr[sepref_fr_rules]:
  \<open>(imp_term, RETURN o import_term) \<in> (arr_with_len_assn stra_assn)\<^sup>k \<rightarrow>\<^sub>a monom_assn\<close>
  using imp_term_is_import unfolding is_import_def import_term_def .

subsection \<open>Coefficients\<close>

abbreviation \<open>sgn_assn \<equiv> unat_assn' TYPE(8)\<close>

text \<open>The sign byte of the C interface: \<open>1\<close> means negated. A malformed number
  string yields coefficient \<open>0\<close> (\<open>slice_to_big_int\<close> returns \<open>int0\<close> then),
  which makes the checker reject the proof later on.\<close>
definition parse_coeff :: \<open>char list \<Rightarrow> nat \<Rightarrow> int\<close> where
  \<open>parse_coeff s sg =
     (case slice_to_big_int s of (ok, v) \<Rightarrow> if sg = 1 then - v else v)\<close>

definition parse_coeff_m :: \<open>char list \<Rightarrow> nat \<Rightarrow> int nres\<close> where
  \<open>parse_coeff_m s sg = doN {
     (ok, v) \<leftarrow> RETURN (slice_to_big_int s);
     if sg = 1 then RETURN (- v) else RETURN v
   }\<close>

lemma parse_coeff_m_correct:
  \<open>(uncurry parse_coeff_m, uncurry (RETURN oo parse_coeff))
    \<in> Id \<times>\<^sub>r Id \<rightarrow>\<^sub>f \<langle>Id\<rangle>nres_rel\<close>
  by (intro frefI nres_relI)
    (auto simp: parse_coeff_m_def parse_coeff_def split: prod.splits)

sepref_def imp_coeff is \<open>uncurry parse_coeff_m\<close>
  :: \<open>stra_assn\<^sup>k *\<^sub>a sgn_assn\<^sup>k \<rightarrow>\<^sub>a sbi_assn\<close>
  unfolding parse_coeff_m_def
  apply (annot_unat_const \<open>TYPE(8)\<close>)
  by sepref

sepref_register parse_coeff
lemmas parse_coeff_hnr[sepref_fr_rules] =
  imp_coeff.refine[FCOMP parse_coeff_m_correct]

subsection \<open>Monomials\<close>

text \<open>The C layout is \<open>(coefficient slice, sign, term)\<close>; the checker layout is
  \<open>(term, coefficient)\<close>.\<close>
definition parse_monomial
  :: \<open>char list \<times> nat \<times> char list list \<Rightarrow> char list list \<times> int\<close> where
  \<open>parse_monomial \<equiv> \<lambda>(s, sg, t). (import_term t, parse_coeff s sg)\<close>

definition parse_monomial_m
  :: \<open>char list \<times> nat \<times> char list list \<Rightarrow> (char list list \<times> int) nres\<close> where
  \<open>parse_monomial_m \<equiv> \<lambda>(s, sg, t). doN {
     c \<leftarrow> RETURN (parse_coeff s sg);
     n \<leftarrow> RETURN (import_term t);
     RETURN (n, c)
   }\<close>

lemma parse_monomial_m_import_fref:
  \<open>(parse_monomial_m, RETURN o COPY) \<in> br parse_monomial (\<lambda>_. True) \<rightarrow>\<^sub>f \<langle>Id\<rangle>nres_rel\<close>
  by (intro frefI nres_relI)
    (auto simp: parse_monomial_m_def parse_monomial_def in_br_conv)

sepref_def imp_monomial is \<open>parse_monomial_m\<close>
  :: \<open>(stra_assn \<times>\<^sub>a sgn_assn \<times>\<^sub>a arr_with_len_assn stra_assn)\<^sup>k \<rightarrow>\<^sub>a monomial_assn\<close>
  unfolding parse_monomial_m_def
  by sepref

definition c_mnml_assn :: \<open>char list list \<times> int \<Rightarrow> c_monomial \<Rightarrow> assn\<close> where
  \<open>c_mnml_assn \<equiv> hr_comp
     (stra_assn \<times>\<^sub>a sgn_assn \<times>\<^sub>a arr_with_len_assn stra_assn)
     (br parse_monomial (\<lambda>_. True))\<close>

context notes [fcomp_norm_unfold] = c_mnml_assn_def[symmetric] begin
lemma imp_monomial_is_import: \<open>is_import c_mnml_assn monomial_assn imp_monomial\<close>
  unfolding is_import_def
  by (rule imp_monomial.refine[FCOMP parse_monomial_m_import_fref])
end

subsection \<open>Polynomials\<close>

abbreviation \<open>c_poly_assn \<equiv> arr_with_len_assn c_mnml_assn\<close>

definition imp_poly :: \<open>c_polynomial \<Rightarrow> poly_conc llM\<close> where [llvm_code]:
  \<open>imp_poly \<equiv> \<lambda>(ni, ai). arr_to_list_import_impl imp_monomial ni ai\<close>

lemmas arr_to_list_import_mnml_inline[llvm_inline] =
  arr_to_list_import_impl_def[OF imp_monomial_is_import]

lemma imp_poly_is_import: \<open>is_import c_poly_assn polynomial_assn imp_poly\<close>
  using arr_to_list_import_is_import[OF imp_monomial_is_import]
  unfolding imp_poly_def .

definition import_poly :: \<open>llist_polynomial \<Rightarrow> llist_polynomial\<close> where
  \<open>import_poly \<equiv> COPY\<close>

sepref_register import_poly

lemma import_poly_hnr[sepref_fr_rules]:
  \<open>(imp_poly, RETURN o import_poly) \<in> c_poly_assn\<^sup>k \<rightarrow>\<^sub>a polynomial_assn\<close>
  using imp_poly_is_import unfolding is_import_def import_poly_def .

abbreviation imp_target :: \<open>c_target \<Rightarrow> poly_conc llM\<close> where
  \<open>imp_target \<equiv> imp_poly\<close>

subsection \<open>The constant-one polynomial\<close>

text \<open>A summand without an explicit coefficient polynomial (\<open>poly_ptr = NULL\<close>)
  denotes the polynomial \<open>1\<close>.\<close>

definition poly_one :: \<open>llist_polynomial\<close> where
  \<open>poly_one = [([], 1)]\<close>

sepref_def poly_one_impl is \<open>uncurry0 (RETURN poly_one)\<close>
  :: \<open>unit_assn\<^sup>k \<rightarrow>\<^sub>a polynomial_assn\<close>
  unfolding poly_one_def
  by sepref

subsection \<open>Summands\<close>

definition poly_ptr_assn :: \<open>llist_polynomial \<Rightarrow> c_polynomial ptr \<Rightarrow> assn\<close> where
  \<open>poly_ptr_assn p \<equiv> \<lambda>ppi. if ppi = null then \<up>(p = poly_one)
     else (EXS pc. \<upharpoonleft>ll_bpto pc ppi ** c_poly_assn p pc)\<close>

definition imp_summand_poly :: \<open>c_polynomial ptr \<Rightarrow> poly_conc llM\<close> where [llvm_code]:
  \<open>imp_summand_poly ppi = (if ppi = null then poly_one_impl
     else doM { pc \<leftarrow> ll_load ppi; imp_poly pc })\<close>

lemma imp_summand_poly_is_import:
  \<open>is_import poly_ptr_assn polynomial_assn imp_summand_poly\<close>
  unfolding is_import_def
  supply [vcg_rules] = hfref_htriple_k0[OF poly_one_impl.refine]
    hfref_htriple_k1[OF imp_poly_is_import[unfolded is_import_def]]
  apply sepref_to_hoare
  apply (clarsimp simp: refine_pw_simps)
  subgoal for p ppi
    apply (cases \<open>ppi = null\<close>)
    subgoal
      apply (simp add: poly_ptr_assn_def imp_summand_poly_def; vcg)
      by (auto simp: ENTAILS_def entails_def sep_algebra_simps pure_def)
    subgoal
      apply (simp add: poly_ptr_assn_def imp_summand_poly_def)
      apply vcg
      apply (auto simp: ENTAILS_def entails_def sep_algebra_simps pure_def)
      by (metis (no_types, lifting) sep.add_ac(1) sep_conj_commuteI)
    done
  done

abbreviation \<open>c_summand_assn \<equiv> poly_ptr_assn \<times>\<^sub>a si64_assn\<close>

definition imp_summand :: \<open>c_summand \<Rightarrow> (poly_conc \<times> 64 word) llM\<close>
  where [llvm_code, llvm_inline]:
  \<open>imp_summand \<equiv> \<lambda>(ppi, ii). doM {
     p \<leftarrow> imp_summand_poly ppi; i \<leftarrow> Mreturn ii; Mreturn (p, i) }\<close>

lemma imp_summand_is_import:
  \<open>is_import c_summand_assn (polynomial_assn \<times>\<^sub>a si64_assn) imp_summand\<close>
  using is_import_prod[OF imp_summand_poly_is_import si64_is_import]
  unfolding imp_summand_def .

definition imp_srcs :: \<open>c_summands \<Rightarrow> srcs_conc llM\<close> where [llvm_code]:
  \<open>imp_srcs \<equiv> \<lambda>(ni, ai). arr_to_list_import_impl imp_summand ni ai\<close>

lemmas arr_to_list_import_summand_inline[llvm_inline] =
  arr_to_list_import_impl_def[OF imp_summand_is_import]

abbreviation \<open>c_summands_assn \<equiv> arr_with_len_assn c_summand_assn\<close>

lemma imp_srcs_is_import: \<open>is_import c_summands_assn srcs_assn imp_srcs\<close>
  using arr_to_list_import_is_import[OF imp_summand_is_import]
  unfolding imp_srcs_def .

subsection \<open>Proof steps\<close>

text \<open>Hoare triples for the step constructors, derived from their
  \<open>sepref\<close> rules.\<close>

lemma mk_cl_rule:
  \<open>llvm_htriple (srcs_assn a ai ** si64_assn n ni ** polynomial_assn p ri)
     (mk_cl_impl ai ni ri)
     (\<lambda>r. lpac_step_assn (CL a n p) r ** si64_assn n ni)\<close>
  unfolding mk_cl_impl_def
  by (vcg; auto simp: step_pure_reassembly)

lemma mk_lext_rule:
  \<open>llvm_htriple (si64_assn n ni ** strl_assn' v vi ** polynomial_assn p ri)
     (mk_lext_impl ni vi ri)
     (\<lambda>r. lpac_step_assn (Extension n v p) r ** si64_assn n ni)\<close>
  unfolding mk_lext_impl_def
  by (vcg; auto simp: step_pure_reassembly)

lemma mk_ldel_rule:
  \<open>llvm_htriple (si64_assn i ii) (mk_ldel_impl ii)
     (\<lambda>r. lpac_step_assn (Del i) r ** si64_assn i ii)\<close>
  unfolding mk_ldel_impl_def
  by (vcg; auto simp: step_pure_reassembly)

text \<open>The parsed view of a C rule is the step itself. The tag convention of
  the C interface is \<open>0 \<mapsto> CL\<close>, \<open>1 \<mapsto> Del\<close>, anything else \<open>\<mapsto> Extension\<close>.\<close>

definition c_rule_assn :: \<open>lpac_step_hol \<Rightarrow> c_rule \<Rightarrow> assn\<close> where
  \<open>c_rule_assn step \<equiv> \<lambda>(t, u). case step of
    CL srcs ni res \<Rightarrow> \<up>(t = 0 \<and> is_U3a u) **
      (case the_u3a u of (nii, smdsi, resi) \<Rightarrow>
         si64_assn ni nii ** c_summands_assn srcs smdsi ** c_poly_assn res resi)
  | Extension ni v res \<Rightarrow> \<up>(t \<noteq> 0 \<and> t \<noteq> 1 \<and> is_U3c u) **
      (case the_u3c u of (nii, vsli, resi) \<Rightarrow>
         si64_assn ni nii ** stra_assn v vsli ** c_poly_assn res resi)
  | Del i \<Rightarrow> \<up>(t = 1 \<and> is_U3b u) ** si64_assn i (the_u3b u)\<close>

lemma c_rule_assn_CL[simp]:
  \<open>c_rule_assn (CL srcs ni res) (t, u) =
    (\<up>(t = 0 \<and> is_U3a u) **
      (case the_u3a u of (nii, smdsi, resi) \<Rightarrow>
         si64_assn ni nii ** c_summands_assn srcs smdsi ** c_poly_assn res resi))\<close>
  unfolding c_rule_assn_def by simp

lemma c_rule_assn_Extension[simp]:
  \<open>c_rule_assn (Extension ni v res) (t, u) =
    (\<up>(t \<noteq> 0 \<and> t \<noteq> 1 \<and> is_U3c u) **
      (case the_u3c u of (nii, vsli, resi) \<Rightarrow>
         si64_assn ni nii ** stra_assn v vsli ** c_poly_assn res resi))\<close>
  unfolding c_rule_assn_def by simp

lemma c_rule_assn_Del[simp]:
  \<open>c_rule_assn (Del i) (t, u) = (\<up>(t = 1 \<and> is_U3b u) ** si64_assn i (the_u3b u))\<close>
  unfolding c_rule_assn_def by simp

definition imp_step :: \<open>c_rule \<Rightarrow> lpac_step_conc llM\<close> where [llvm_code]:
  \<open>imp_step \<equiv> \<lambda>(t, u). doM {
     if t = 0 then doM {
       lc \<leftarrow> ll_u3_extr_a u;
       case lc of (nii, smdsi, resi) \<Rightarrow> doM {
         srcsi \<leftarrow> imp_srcs smdsi;
         ri \<leftarrow> imp_poly resi;
         mk_cl_impl srcsi nii ri
       }
     } else if t = 1 then doM {
       ii \<leftarrow> ll_u3_extr_b u;
       mk_ldel_impl ii
     } else doM {
       er \<leftarrow> ll_u3_extr_c u;
       case er of (nii, vsli, resi) \<Rightarrow> doM {
         vi \<leftarrow> slice_to_str_impl vsli;
         ri \<leftarrow> imp_poly resi;
         mk_lext_impl nii vi ri
       }
     }
   }\<close>

lemma imp_step_is_import: \<open>is_import c_rule_assn lpac_step_assn imp_step\<close>
  unfolding is_import_def
  supply [vcg_rules] = mk_cl_rule mk_lext_rule mk_ldel_rule
    hfref_htriple_k1[OF imp_srcs_is_import[unfolded is_import_def]]
    hfref_htriple_k1[OF imp_poly_is_import[unfolded is_import_def]]
    hfref_htriple_k1[OF slice_to_str_is_import[unfolded is_import_def]]
  apply sepref_to_hoare
  apply (clarsimp simp: refine_pw_simps)
  subgoal for step tu
    apply (cases tu)
    subgoal for t u
      apply (cases step)
      subgoal for srcs n res
        apply (clarsimp simp: imp_step_def)
        apply vcg
        apply (auto simp: step_pure_reassembly)
        by (auto simp: sep_conj_aci)
      subgoal for n v res
        apply (clarsimp simp: imp_step_def)
        apply vcg
        apply (auto simp: step_pure_reassembly)
        by (auto simp: sep_conj_aci)
      subgoal for i
        apply (clarsimp simp: imp_step_def)
        apply vcg
        by (auto simp: step_pure_reassembly)
      done
    done

subsection \<open>The proof (rule list)\<close>

definition imp_proof :: \<open>c_proof \<Rightarrow> lpac_step_conc cl_list llM\<close> where [llvm_code]:
  \<open>imp_proof \<equiv> \<lambda>(ni, ai). arr_to_list_import_impl imp_step ni ai\<close>

lemmas arr_to_list_import_step_inline[llvm_inline] =
  arr_to_list_import_impl_def[OF imp_step_is_import]

lemma imp_proof_is_import:
  \<open>is_import (arr_with_len_assn c_rule_assn) (cl_assn' lpac_step_assn) imp_proof\<close>
  using arr_to_list_import_is_import[OF imp_step_is_import]
  unfolding imp_proof_def .

subsection \<open>Inputs (indexed polynomials as a finite map)\<close>

abbreviation \<open>c_input_assn \<equiv> si64_assn \<times>\<^sub>a c_poly_assn\<close>

definition imp_input :: \<open>c_input \<Rightarrow> (64 word \<times> poly_conc) llM\<close>
  where [llvm_code, llvm_inline]:
  \<open>imp_input \<equiv> \<lambda>(ii, ai). doM {
     i \<leftarrow> Mreturn ii; p \<leftarrow> imp_poly ai; Mreturn (i, p) }\<close>

lemma imp_input_is_import:
  \<open>is_import c_input_assn (si64_assn \<times>\<^sub>a polynomial_assn) imp_input\<close>
  using is_import_prod[OF si64_is_import imp_poly_is_import]
  unfolding imp_input_def .

text \<open>The checker consumes the inputs as a finite map; the import loop builds
  it directly with \<open>fmupd\<close> while walking the C array.\<close>

definition inputs_fmap
  :: \<open>(nat \<times> llist_polynomial) list \<Rightarrow> (nat, llist_polynomial) fmap\<close> where
  \<open>inputs_fmap xs = fold (\<lambda>(k, p) m. fmupd k p m) xs fmempty\<close>

definition inputs_fmap_n
  :: \<open>nat \<Rightarrow> (nat \<times> llist_polynomial) list \<Rightarrow> (nat, llist_polynomial) fmap\<close> where
  \<open>inputs_fmap_n n xs = inputs_fmap xs\<close>

definition imp_inputs_m
  :: \<open>nat \<Rightarrow> (nat \<times> llist_polynomial) list \<Rightarrow> (nat, llist_polynomial) fmap nres\<close>
  where
  \<open>imp_inputs_m n xs = doN {
     ASSERT (n = length xs \<and> n < max_snat 64);
     (m, _) \<leftarrow> WHILEIT
       (\<lambda>(m, i). i \<le> n \<and> m = fold (\<lambda>(k, p) m. fmupd k p m) (take i xs) fmempty)
       (\<lambda>(_, i). i < n)
       (\<lambda>(m, i). doN {
          ASSERT (i < n);
          (k, p) \<leftarrow> mop_list_get xs i;
          RETURN (fmupd k p m, i + 1)
        })
       (fmempty, 0);
     RETURN m
   }\<close>

lemma imp_inputs_m_le:
  assumes \<open>n = length xs\<close> and \<open>n < max_snat 64\<close>
  shows \<open>imp_inputs_m n xs \<le> RETURN (inputs_fmap xs)\<close>
  unfolding imp_inputs_m_def mop_list_get_alt inputs_fmap_def
  apply (refine_vcg WHILEIT_rule[where R=\<open>measure (\<lambda>(_, i). n - i)\<close>])
  using assms
  apply (clarsimp_all simp: take_Suc_conv_app_nth split: prod.splits)
  using diff_less_mono2 by blast

lemma imp_inputs_m_correct:
  \<open>(uncurry imp_inputs_m, uncurry (RETURN oo inputs_fmap_n))
    \<in> [\<lambda>(n, xs). n = length xs \<and> n < max_snat 64]\<^sub>f Id \<times>\<^sub>r Id \<rightarrow> \<langle>Id\<rangle>nres_rel\<close>
  by (intro frefI nres_relI)
    (auto simp: inputs_fmap_n_def intro!: imp_inputs_m_le)

sepref_def imp_inputs_arr is \<open>uncurry imp_inputs_m\<close>
  :: \<open>si64_assn\<^sup>k *\<^sub>a (woarray_assn c_input_assn)\<^sup>k \<rightarrow>\<^sub>a polys_assn\<close>
  unfolding imp_inputs_m_def op_fmap_empty_def[symmetric]
  supply [sepref_fr_rules] = wo_nth_import_hnr[OF imp_input_is_import]
  apply (annot_snat_const size_t)
  apply sepref_dbg_keep
  apply sepref_dbg_trans_keep

lemmas imp_inputs_arr_hnr = imp_inputs_arr.refine[FCOMP imp_inputs_m_correct]

definition imp_inputs where [llvm_code]:
  \<open>imp_inputs \<equiv> \<lambda>(ni, ai). imp_inputs_arr ni ai\<close>

lemma imp_inputs_import:
  \<open>(imp_inputs, RETURN o inputs_fmap)
    \<in> (arr_with_len_assn c_input_assn)\<^sup>k \<rightarrow>\<^sub>a polys_assn\<close>
proof -
  note HT = hfref_htriple_k1_k2_guard[OF imp_inputs_arr_hnr]
  show ?thesis
    unfolding imp_inputs_def
    apply sepref_to_hoare
    apply (clarsimp simp: arr_with_len_assn_def)
    subgoal for xs ni ai
      apply (rule htriple_pure_preI)
      apply (clarsimp dest!: pure_part_split_conj)
      subgoal premises prems
      proof -
        have PRE: \<open>(\<lambda>(n, arr). n = length arr \<and> n < max_snat 64) (length xs, xs)\<close>
          using prems snat_lt_max_snat[of ni] by (auto simp: snat.assn_def)
        show ?thesis
          using HT[OF PRE, of ni ai]
          by (simp add: inputs_fmap_n_def pure_app_eq in_snat_rel_conv_assn
            snat.assn_is_rel[symmetric] snat_rel_def sep_algebra_simps)
      qed
      done
    done
qed

section \<open>Checker Entry Points\<close>

text \<open>The entry points below are the remaining trusted glue: load the three
  C structures, import them through the verified importers, run the verified
  checker and return the status byte.\<close>

definition run_checker :: \<open>c_inputs ptr \<Rightarrow> c_proof ptr \<Rightarrow> c_target ptr \<Rightarrow> 8 word llM\<close>
  where [llvm_code]:
  \<open>run_checker \<equiv> \<lambda>cinpsp cprfp ctgtp. doM {
    cinps \<leftarrow> ll_load cinpsp;
    cprf \<leftarrow> ll_load cprfp;
    ctgt \<leftarrow> ll_load ctgtp;
    isatgt \<leftarrow> imp_target ctgt;
    isainps \<leftarrow> imp_inputs cinps;
    isaprf \<leftarrow> imp_proof cprf;
    ((st, msg), vsp) \<leftarrow> full_checker_l_impl isatgt isainps isaprf;
    Mreturn st
  }\<close>

export_llvm
  run_checker is \<open>char run_checker(inputs*, proof*, polynomial*)\<close>
  defines \<open>
    typedef struct {uint64_t len; char *ptr;} slice;
    typedef struct {uint64_t num_vars; slice *vars_ptr;} term;
    typedef struct {slice coeff; struct {char neg; term vars;};} monomial;
    typedef struct {uint64_t num_mnmls; monomial *mnmls_ptr;} polynomial;
    typedef struct {uint64_t idx; polynomial poly;} input;
    typedef struct {uint64_t num_inputs; input *inputs;} inputs;
    typedef struct {polynomial *poly_ptr; uint64_t idx;} summand;
    typedef struct {uint64_t num_summands; summand *summands_ptr;} summands;
    typedef struct {uint64_t target_idx; struct {summands summands; polynomial res;};} lc_rule;
    typedef struct {uint64_t idx; struct {slice var; polynomial poly;};} ext_rule;
    typedef struct {int32_t typ; union {lc_rule lc; uint64_t del; ext_rule ext;} u;} rule;
    typedef struct {uint64_t num_rules; rule *rules_ptr;} proof;
  \<close>
  file "./code/pasteque.ll"

text \<open>Efficient checker\<close>

definition run_shared_checker
  :: \<open>c_inputs ptr \<Rightarrow> c_proof ptr \<Rightarrow> c_target ptr \<Rightarrow> 8 word llM\<close>
  where [llvm_code]:
  \<open>run_shared_checker \<equiv> \<lambda>cinpsp cprfp ctgtp. doM {
    cinps \<leftarrow> ll_load cinpsp;
    cprf \<leftarrow> ll_load cprfp;
    ctgt \<leftarrow> ll_load ctgtp;
    isatgt \<leftarrow> imp_target ctgt;
    isainps \<leftarrow> imp_inputs cinps;
    isaprf \<leftarrow> imp_proof cprf;
    ((st, msg), vsp) \<leftarrow> full_checker_l_s2_impl isatgt isainps isaprf;
    Mreturn st
  }\<close>

export_llvm
  run_shared_checker is \<open>char run_shared_checker(inputs*, proof*, polynomial*)\<close>
  defines \<open>
    typedef struct {uint64_t len; char *ptr;} slice;
    typedef struct {uint64_t num_vars; slice *vars_ptr;} term;
    typedef struct {slice coeff; struct {char neg; term vars;};} monomial;
    typedef struct {uint64_t num_mnmls; monomial *mnmls_ptr;} polynomial;
    typedef struct {uint64_t idx; polynomial poly;} input;
    typedef struct {uint64_t num_inputs; input *inputs;} inputs;
    typedef struct {polynomial *poly_ptr; uint64_t idx;} summand;
    typedef struct {uint64_t num_summands; summand *summands_ptr;} summands;
    typedef struct {uint64_t target_idx; struct {summands summands; polynomial res;};} lc_rule;
    typedef struct {uint64_t idx; struct {slice var; polynomial poly;};} ext_rule;
    typedef struct {int32_t typ; union {lc_rule lc; uint64_t del; ext_rule ext;} u;} rule;
    typedef struct {uint64_t num_rules; rule *rules_ptr;} proof;
  \<close>
  file "./code/pasteque_shared.ll"

end
