theory LPAC_CodeExport
  imports
    LPAC_Checker_Synthesis
    BigInt_String
begin

text \<open>This theory defines types for the c interface and also handles importing
  the data generated by the c parser into the target datatypes of the verified
  parser. Note that functions in here are not verified, so they are part of the
  trusted code base.

  The types below mirror the \<open>Isabelle facing types\<close> section of
  \<open>code/pasteque.c\<close>. A few representation choices are forced by the
  Isabelle-LLVM code generator and are worth keeping in mind when reconciling
  this file with the C side:

  \<^item> Isabelle products \<open>a \<times> b \<times> c\<close> are right-nested binary pairs, so a C struct
    with more than two fields becomes a nested LLVM struct. To keep the exported
    header layout-compatible with the flat C structs we describe the extra
    fields as C11 \<^emph>\<open>anonymous\<close> nested structs (same byte layout, same member
    access as the flat definition in \<open>code/pasteque.c\<close>).
  \<^item> HOL has no one-element product, so single-field C structs collapse to their
    field: \<open>del_rule\<close> becomes \<^typ>\<open>64 word\<close> and \<open>target\<close> becomes \<open>c_polynomial\<close>.
  \<^item> The code generator has no \<open>bool\<close> or \<open>enum\<close> keyword, so \<open>bool neg\<close> is exported
    as \<open>char\<close> and the \<open>rule_type\<close> enum as \<open>int32_t\<close> (both layout-compatible).
  \<^item> Anonymous unions are printed as anonymous structs by the code generator
    (both share the \<open>FLD_ANON\<close> case), which would give the wrong layout. The
    tagged union in \<open>rule\<close> is therefore given a named field \<open>u\<close>, i.e. it is
    accessed as \<open>r.u.lc\<close> instead of \<open>r.lc\<close>.
  \<^item> All length-carrying arrays are ordered \<^emph>\<open>length first, pointer second\<close>,
    matching the concrete representation of the IICF length-carrying array
    \<^typ>\<open>('x,'l) larray\<close> \<open>= 'l word \<times> 'x ptr\<close> (@{theory Isabelle_LLVM.IICF_Array}).
    A C array struct is thus bit-identical to a \<open>larray_assn' TYPE(64)\<close> value and
    can be passed to verified import functions without any glue code. The C side
    must uphold the \<open>larray\<close> invariants: lengths below \<open>2^63\<close> (\<open>snat\<close>) and a
    \<^emph>\<open>null\<close> pointer for empty arrays (\<open>narray_assn\<close> demands \<open>p = null\<close> for \<open>[]\<close>).\<close>

section \<open>A ternary union type\<close>

text \<open>The library only ships the binary union example \<open>ll_sum\<close> (and not in the
  IICF import). The tagged union in \<open>rule\<close> has three members, so we provide a
  ternary union type, modelled on \<open>ll_sum\<close>.\<close>

declare [[llc_compile_union=true]]

datatype ('a,'b,'c) ll_union3 =
    is_U3Zero: U3Zero
  | is_U3a: U3a (the_u3a: 'a)
  | is_U3b: U3b (the_u3b: 'b)
  | is_U3c: U3c (the_u3c: 'c)

instantiation ll_union3 :: (llvm_rep,llvm_rep,llvm_rep) llvm_rep
begin
  fun to_val_ll_union3 :: \<open>('a,'b,'c) ll_union3 \<Rightarrow> llvm_val\<close> where
    "to_val_ll_union3 U3Zero = LL_UNION (UN_ZERO_INIT [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3a x) = LL_UNION (UN_SEL [] (to_val x) [struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3b x) = LL_UNION (UN_SEL [struct_of TYPE('a)] (to_val x) [struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3c x) = LL_UNION (UN_SEL [struct_of TYPE('a), struct_of TYPE('b)] (to_val x) [])"

  fun from_val_ll_union3 :: \<open>llvm_val \<Rightarrow> ('a,'b,'c) ll_union3\<close> where
    "from_val_ll_union3 (LL_UNION (UN_ZERO_INIT _)) = U3Zero"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [] x [_,_])) = U3a (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_] x [_])) = U3b (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_,_] x [])) = U3c (from_val x)"
  | "from_val_ll_union3 _ = undefined"

  definition [simp]: "struct_of_ll_union3 (_::('a,'b,'c) ll_union3 itself) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  definition [simp]: "init_ll_union3 = U3Zero"

  instance
    apply standard
    apply (all \<open>(clarsimp simp: comp_def fun_eq_iff)?\<close>)
    subgoal for x by (cases x) auto
    subgoal for v by (cases v rule: from_val_ll_union3.cases) auto
    subgoal for x by (cases x) auto
    done
end

lemma struct_of_ll_union3[ll_struct_of]:
  "struct_of TYPE(('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  by simp

text \<open>Member extractors, modelled on \<open>ll_sum_extr_left\<close>/\<open>ll_sum_extr_right\<close>. Only
  extraction is provided (no makers): the C side constructs the unions, the import
  layer only reads them.\<close>

definition ll_u3_extr_a :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'a llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_a x \<equiv> ll_dest_union x 0\<close>

definition ll_u3_extr_b :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'b llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_b x \<equiv> ll_dest_union x 1\<close>

definition ll_u3_extr_c :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'c llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_c x \<equiv> ll_dest_union x 2\<close>

lemma ll_u3_extr_simps:
  \<open>is_U3a x \<Longrightarrow> ll_u3_extr_a x = Mreturn (the_u3a x)\<close>
  \<open>is_U3b x \<Longrightarrow> ll_u3_extr_b x = Mreturn (the_u3b x)\<close>
  \<open>is_U3c x \<Longrightarrow> ll_u3_extr_c x = Mreturn (the_u3c x)\<close>
  unfolding ll_u3_extr_a_def ll_u3_extr_b_def ll_u3_extr_c_def
  by (cases x; simp add: ll_dest_union_def checked_from_val_def llvm_dest_union_def)+

lemma ll_u3_extr_rules[vcg_rules]:
  \<open>llvm_htriple (\<up>(is_U3a x)) (ll_u3_extr_a x) (\<lambda>r. \<up>(r = the_u3a x))\<close>
  \<open>llvm_htriple (\<up>(is_U3b x)) (ll_u3_extr_b x) (\<lambda>r. \<up>(r = the_u3b x))\<close>
  \<open>llvm_htriple (\<up>(is_U3c x)) (ll_u3_extr_c x) (\<lambda>r. \<up>(r = the_u3c x))\<close>
  supply [vcg_normalize_simps] = ll_u3_extr_simps
  by vcg


section \<open>C Interface Types\<close>

text \<open>We describe the datatypes that will be instanciated by the c parser.\<close>

\<comment> \<open>BASICs: \<open>slice\<close>, \<open>term\<close>, \<open>monomial\<close>, \<open>polynomial\<close>. Arrays are \<open>(length, pointer)\<close>
  pairs, i.e. \<open>larray\<close>s.\<close>
type_synonym c_slice = \<open>64 word \<times> 8 word ptr\<close>
type_synonym c_term = \<open>64 word \<times> c_slice ptr\<close>
\<comment> \<open>\<open>monomial = {slice coeff; bool neg; term vars}\<close> (\<open>neg\<close> as \<^typ>\<open>8 word\<close>)\<close>
type_synonym c_monomial = \<open>c_slice \<times> 8 word \<times> c_term\<close>
type_synonym c_polynomial = \<open>64 word \<times> c_monomial ptr\<close>

\<comment> \<open>INPUTS / SPEC\<close>
type_synonym c_input = \<open>64 word \<times> c_polynomial\<close>
type_synonym c_inputs = \<open>64 word \<times> c_input ptr\<close>

\<comment> \<open>PROOF\<close>
\<comment> \<open>\<open>summand = {polynomial *poly_ptr; u64 idx}\<close> \<emdash> a (pointer, index) pair, not an
  array, so it is unaffected by the \<open>larray\<close> ordering convention\<close>
type_synonym c_summand = \<open>c_polynomial ptr \<times> 64 word\<close>
type_synonym c_summands = \<open>64 word \<times> c_summand ptr\<close>
\<comment> \<open>\<open>lc_rule = {u64 target_idx; summands summands; polynomial res}\<close>\<close>
type_synonym c_lc_rule = \<open>64 word \<times> c_summands \<times> c_polynomial\<close>
\<comment> \<open>\<open>del_rule = {u64 idx}\<close>; single-field struct collapses to its field\<close>
type_synonym c_del_rule = \<open>64 word\<close>
\<comment> \<open>\<open>ext_rule = {u64 idx; slice var; polynomial poly}\<close>\<close>
type_synonym c_ext_rule = \<open>64 word \<times> c_slice \<times> c_polynomial\<close>
\<comment> \<open>\<open>rule = {rule_type typ; union {lc_rule lc; del_rule del; ext_rule ext}}\<close>
  (\<open>typ\<close> as \<^typ>\<open>32 word\<close>, \<open>del\<close> collapsed to \<^typ>\<open>64 word\<close>)\<close>
type_synonym c_rule = \<open>32 word \<times> (c_lc_rule, c_del_rule, c_ext_rule) ll_union3\<close>
type_synonym c_proof = \<open>64 word \<times> c_rule ptr\<close>

\<comment> \<open>TARGET: \<open>target = {polynomial poly}\<close>; single-field struct collapses to its field\<close>
type_synonym c_target = \<open>c_polynomial\<close>


section \<open>Exported C header\<close>

text \<open>Placeholder entry points, so that \<open>export_llvm\<close> emits the interface types
  into the generated header. They are replaced by the real (unverified) import
  functions once those are written.\<close>

definition parse_inputs :: \<open>c_inputs ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>parse_inputs \<equiv> \<lambda>a. Mreturn 0\<close>
definition parse_proof :: \<open>c_proof ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>parse_proof \<equiv> \<lambda>a. Mreturn 0\<close>
definition parse_target :: \<open>c_target ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>parse_target \<equiv> \<lambda>a. Mreturn 0\<close>

export_llvm
  parse_inputs is \<open>char parse_inputs(inputs*)\<close>
  parse_proof is \<open>char parse_proof(proof*)\<close>
  parse_target is \<open>char parse_target(polynomial*)\<close>
  defines \<open>
    typedef struct {uint64_t len; char *ptr;} slice;
    typedef struct {uint64_t num_vars; slice *vars_ptr;} term;
    typedef struct {slice coeff; struct {char neg; term vars;};} monomial;
    typedef struct {uint64_t num_mnmls; monomial *mnmls_ptr;} polynomial;
    typedef struct {uint64_t idx; polynomial poly;} input;
    typedef struct {uint64_t num_inputs; input *inputs;} inputs;
    typedef struct {polynomial *poly_ptr; uint64_t idx;} summand;
    typedef struct {uint64_t num_summands; summand *summands_ptr;} summands;
    typedef struct {uint64_t target_idx; struct {summands summands; polynomial res;};} lc_rule;
    typedef struct {uint64_t idx; struct {slice var; polynomial poly;};} ext_rule;
    typedef struct {int32_t typ; union {lc_rule lc; uint64_t del; ext_rule ext;} u;} rule;
    typedef struct {uint64_t num_rules; rule *rules_ptr;} proof;
  \<close>
  file "/tmp/pasteque_interface.ll"


section \<open>Importing the C-Parsed Structures\<close>

text \<open>Trusted (unverified) glue between the C parser and the verified checker:
  walk the C-facing structs defined above and build
  the checker's owned input structures through the \<^emph>\<open>verified\<close> leaf converters
  and structure builders. Only the pointer chasing and array loops in this theory
  are trusted; every value conversion and every allocation happens in verified
  code (\<open>larr_to_os_copy\<close>, \<open>int_of_bytes_impl\<close>, \<open>poly_one_impl\<close>, \<open>os_prepend\<close>,
  \<open>CL_impl\<close>/\<open>Extension_impl\<close>/\<open>Del_impl\<close>).

  \<^bold>\<open>C-side contract\<close> (checked by the C parser, assumed here):

  \<^item> Arrays are \<open>(len, ptr)\<close> pairs (\<open>larray\<close> layout), \<open>len < 2^63\<close> (\<open>snat\<close>), and
    \<open>ptr = NULL\<close> iff \<open>len = 0\<close>.
  \<^item> Coefficient slices are nonempty ASCII digit strings, most-significant digit
    first, without sign (the \<open>neg\<close> flag is separate); an implicit coefficient of
    \<open>1\<close> is materialized by the parser.
  \<^item> \<open>summand.poly_ptr\<close> may be \<open>NULL\<close>, denoting an implicit factor of \<open>1\<close>.
  \<^item> Rule tags follow the C \<open>rule_type\<close> enum: \<open>S_LINCOM = 0\<close>, \<open>S_DEL = 1\<close>,
    \<open>S_EXT = 2\<close>. These are \<^emph>\<open>translated\<close> (never copied) into the
    \<open>pac_step_assn\<close> tags \<open>CL = 0\<close>, \<open>Extension = 1\<close>, \<open>Del = 2\<close>.
  \<^item> Ids fit in \<open>u64\<close> and are range-checked in C.
  \<^item> All C structs are borrowed: this theory never frees C memory; C frees its
    buffers after the checker entry point returns.\<close>

subsection \<open>Concrete Type Abbreviations\<close>

type_synonym mnml_conc = \<open>monom_conc \<times> sbin_conc \<times> 1 word\<close>
type_synonym poly_conc = \<open>mnml_conc os_list\<close>
type_synonym sbi_conc = \<open>sbin_conc \<times> 1 word\<close>
type_synonym strl_conc = \<open>8 word os_list\<close>
type_synonym step_conc = \<open>(poly_conc, strl_conc) pac_step_impl\<close>

subsection \<open>Leaf Imports\<close>

text \<open>A C \<open>slice\<close> \<^emph>\<open>is\<close> a byte \<open>larray\<close>; the verified keep-mode copy converts it
  into an owned string (open char list).\<close>

definition imp_string :: \<open>c_slice \<Rightarrow> strl_conc llM\<close> where [llvm_code]:
  \<open>imp_string s \<equiv> larr_to_os_copy s\<close>

text \<open>Coefficient: digit slice + neg byte \<open>\<rightarrow>\<close> signed big int (verified parse).\<close>

definition imp_coeff :: \<open>c_slice \<Rightarrow> 8 word \<Rightarrow> sbi_conc llM\<close> where [llvm_code]:
  \<open>imp_coeff s neg \<equiv> doM {
     nb \<leftarrow> ll_icmp_ne neg 0;
     int_of_bytes_impl s nb
   }\<close>

subsection \<open>Structure Walks\<close>

text \<open>All walks traverse the C array back-to-front and prepend, preserving file
  order without a final reversal.\<close>

definition imp_monom :: \<open>c_term \<Rightarrow> monom_conc llM\<close> where [llvm_code]:
  \<open>imp_monom \<equiv> \<lambda>(n, a). doM {
     (m, _) \<leftarrow> llc_while
       (\<lambda>(m, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(m, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          s \<leftarrow> array_nth a i;
          str \<leftarrow> imp_string s;
          m \<leftarrow> os_prepend str m;
          Mreturn (m, i)
        }) (null, n);
     Mreturn m
   }\<close>

definition imp_poly :: \<open>c_polynomial \<Rightarrow> poly_conc llM\<close> where [llvm_code]:
  \<open>imp_poly \<equiv> \<lambda>(n, a). doM {
     (p, _) \<leftarrow> llc_while
       (\<lambda>(p, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(p, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          mo \<leftarrow> array_nth a i;
          case mo of (cf, neg, vs) \<Rightarrow> doM {
            c \<leftarrow> imp_coeff cf neg;
            m \<leftarrow> imp_monom vs;
            p \<leftarrow> os_prepend (m, c) p;
            Mreturn (p, i)
          }
        }) (null, n);
     Mreturn p
   }\<close>

definition imp_inputs :: \<open>c_inputs \<Rightarrow> (64 word \<times> poly_conc) os_list llM\<close>
  where [llvm_code]:
  \<open>imp_inputs \<equiv> \<lambda>(n, a). doM {
     (xs, _) \<leftarrow> llc_while
       (\<lambda>(xs, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(xs, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          inp \<leftarrow> array_nth a i;
          case inp of (idx, pc) \<Rightarrow> doM {
            p \<leftarrow> imp_poly pc;
            xs \<leftarrow> os_prepend (idx, p) xs;
            Mreturn (xs, i)
          }
        }) (null, n);
     Mreturn xs
   }\<close>

definition imp_srcs :: \<open>c_summands \<Rightarrow> (poly_conc \<times> 64 word) os_list llM\<close>
  where [llvm_code]:
  \<open>imp_srcs \<equiv> \<lambda>(n, a). doM {
     (xs, _) \<leftarrow> llc_while
       (\<lambda>(xs, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(xs, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          smd \<leftarrow> array_nth a i;
          case smd of (pp, idx) \<Rightarrow> doM {
            q \<leftarrow> if pp = null then poly_one_impl
                else doM { pc \<leftarrow> ll_load pp; imp_poly pc };
            xs \<leftarrow> os_prepend (q, idx) xs;
            Mreturn (xs, i)
          }
        }) (null, n);
     Mreturn xs
   }\<close>

definition imp_step :: \<open>c_rule \<Rightarrow> step_conc llM\<close> where [llvm_code]:
  \<open>imp_step \<equiv> \<lambda>(t, u). doM {
     if t = 0 then doM {          \<comment> \<open>\<open>S_LINCOM\<close> \<open>\<rightarrow>\<close> \<open>CL\<close>\<close>
       lc \<leftarrow> ll_u3_extr_a u;
       case lc of (tidx, smds, res) \<Rightarrow> doM {
         srcs \<leftarrow> imp_srcs smds;
         r \<leftarrow> imp_poly res;
         CL_impl srcs tidx r
       }
     } else if t = 1 then doM {   \<comment> \<open>\<open>S_DEL\<close> \<open>\<rightarrow>\<close> \<open>Del\<close>\<close>
       idx \<leftarrow> ll_u3_extr_b u;
       Del_impl idx
     } else doM {                 \<comment> \<open>\<open>S_EXT\<close> \<open>\<rightarrow>\<close> \<open>Extension\<close>\<close>
       er \<leftarrow> ll_u3_extr_c u;
       case er of (idx, vsl, resp) \<Rightarrow> doM {
         v \<leftarrow> imp_string vsl;
         r \<leftarrow> imp_poly resp;
         Extension_impl idx v r
       }
     }
   }\<close>

definition imp_proof :: \<open>c_proof \<Rightarrow> step_conc os_list llM\<close> where [llvm_code]:
  \<open>imp_proof \<equiv> \<lambda>(n, a). doM {
     (xs, _) \<leftarrow> llc_while
       (\<lambda>(xs, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(xs, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          r \<leftarrow> array_nth a i;
          st \<leftarrow> imp_step r;
          xs \<leftarrow> os_prepend st xs;
          Mreturn (xs, i)
        }) (null, n);
     Mreturn xs
   }\<close>

abbreviation imp_target :: \<open>c_target \<Rightarrow> poly_conc llM\<close> where
  \<open>imp_target \<equiv> imp_poly\<close>

end
