theory LPAC_C_Interface
  imports Isabelle_LLVM.IICF
begin

text \<open>This theory defines types for the c interface and also handles importing
  the data generated by the c parser into the target datatypes of the verified
  parser. Note that functions in here are not verified, so they are part of the
  trusted code base.

  The types below mirror the \<open>Isabelle facing types\<close> section of
  \<open>code/pasteque.c\<close>. A few representation choices are forced by the
  Isabelle-LLVM code generator and are worth keeping in mind when reconciling
  this file with the C side:

  \<^item> Isabelle products \<open>a \<times> b \<times> c\<close> are right-nested binary pairs, so a C struct
    with more than two fields becomes a nested LLVM struct. To keep the exported
    header layout-compatible with the flat C structs we describe the extra
    fields as C11 \<^emph>\<open>anonymous\<close> nested structs (same byte layout, same member
    access as the flat definition in \<open>code/pasteque.c\<close>).
  \<^item> HOL has no one-element product, so single-field C structs collapse to their
    field: \<open>del_rule\<close> becomes \<^typ>\<open>64 word\<close> and \<open>target\<close> becomes \<open>c_polynomial\<close>.
  \<^item> The code generator has no \<open>bool\<close> or \<open>enum\<close> keyword, so \<open>bool neg\<close> is exported
    as \<open>char\<close> and the \<open>rule_type\<close> enum as \<open>int32_t\<close> (both layout-compatible).
  \<^item> Anonymous unions are printed as anonymous structs by the code generator
    (both share the \<open>FLD_ANON\<close> case), which would give the wrong layout. The
    tagged union in \<open>rule\<close> is therefore given a named field \<open>u\<close>, i.e. it is
    accessed as \<open>r.u.lc\<close> instead of \<open>r.lc\<close>.\<close>

section \<open>A ternary union type\<close>

text \<open>The library only ships the binary union example \<open>ll_sum\<close> (and not in the
  IICF import). The tagged union in \<open>rule\<close> has three members, so we provide a
  ternary union type, modelled on \<open>ll_sum\<close>.\<close>

declare [[llc_compile_union=true]]

datatype ('a,'b,'c) ll_union3 =
    is_U3Zero: U3Zero
  | is_U3a: U3a (the_u3a: 'a)
  | is_U3b: U3b (the_u3b: 'b)
  | is_U3c: U3c (the_u3c: 'c)

instantiation ll_union3 :: (llvm_rep,llvm_rep,llvm_rep) llvm_rep
begin
  fun to_val_ll_union3 :: \<open>('a,'b,'c) ll_union3 \<Rightarrow> llvm_val\<close> where
    "to_val_ll_union3 U3Zero = LL_UNION (UN_ZERO_INIT [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3a x) = LL_UNION (UN_SEL [] (to_val x) [struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3b x) = LL_UNION (UN_SEL [struct_of TYPE('a)] (to_val x) [struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3c x) = LL_UNION (UN_SEL [struct_of TYPE('a), struct_of TYPE('b)] (to_val x) [])"

  fun from_val_ll_union3 :: \<open>llvm_val \<Rightarrow> ('a,'b,'c) ll_union3\<close> where
    "from_val_ll_union3 (LL_UNION (UN_ZERO_INIT _)) = U3Zero"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [] x [_,_])) = U3a (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_] x [_])) = U3b (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_,_] x [])) = U3c (from_val x)"
  | "from_val_ll_union3 _ = undefined"

  definition [simp]: "struct_of_ll_union3 (_::('a,'b,'c) ll_union3 itself) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  definition [simp]: "init_ll_union3 = U3Zero"

  instance
    apply standard
    apply (all \<open>(clarsimp simp: comp_def fun_eq_iff)?\<close>)
    subgoal for x by (cases x) auto
    subgoal for v by (cases v rule: from_val_ll_union3.cases) auto
    subgoal for x by (cases x) auto
    done
end

lemma struct_of_ll_union3[ll_struct_of]:
  "struct_of TYPE(('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  by simp


section \<open>C Interface Types\<close>

text \<open>We describe the datatypes that will be instanciated by the c parser.\<close>

\<comment> \<open>BASICs: \<open>slice\<close>, \<open>term\<close>, \<open>monomial\<close>, \<open>polynomial\<close>\<close>
type_synonym c_slice = \<open>8 word ptr \<times> 64 word\<close>
type_synonym c_term = \<open>c_slice ptr \<times> 64 word\<close>
\<comment> \<open>\<open>monomial = {slice coeff; bool neg; term vars}\<close> (\<open>neg\<close> as \<^typ>\<open>8 word\<close>)\<close>
type_synonym c_monomial = \<open>c_slice \<times> 8 word \<times> c_term\<close>
type_synonym c_polynomial = \<open>c_monomial ptr \<times> 64 word\<close>

\<comment> \<open>INPUTS / SPEC\<close>
type_synonym c_input = \<open>64 word \<times> c_polynomial\<close>
type_synonym c_inputs = \<open>c_input ptr \<times> 64 word\<close>

\<comment> \<open>PROOF\<close>
type_synonym c_summand = \<open>c_polynomial ptr \<times> 64 word\<close>
\<comment> \<open>\<open>lc_rule = {u64 target_idx; summand* summands; u64 num_summands; polynomial res}\<close>\<close>
type_synonym c_lc_rule = \<open>64 word \<times> c_summand ptr \<times> 64 word \<times> c_polynomial\<close>
\<comment> \<open>\<open>del_rule = {u64 idx}\<close>; single-field struct collapses to its field\<close>
type_synonym c_del_rule = \<open>64 word\<close>
\<comment> \<open>\<open>ext_rule = {u64 idx; slice var; polynomial poly}\<close>\<close>
type_synonym c_ext_rule = \<open>64 word \<times> c_slice \<times> c_polynomial\<close>
\<comment> \<open>\<open>rule = {rule_type typ; union {lc_rule lc; del_rule del; ext_rule ext}}\<close>
  (\<open>typ\<close> as \<^typ>\<open>32 word\<close>, \<open>del\<close> collapsed to \<^typ>\<open>64 word\<close>)\<close>
type_synonym c_rule = \<open>32 word \<times> (c_lc_rule, c_del_rule, c_ext_rule) ll_union3\<close>
type_synonym c_proof = \<open>c_rule ptr \<times> 64 word\<close>

\<comment> \<open>TARGET: \<open>target = {polynomial poly}\<close>; single-field struct collapses to its field\<close>
type_synonym c_target = \<open>c_polynomial\<close>


section \<open>Exported C header\<close>

text \<open>Placeholder entry points, so that \<open>export_llvm\<close> emits the interface types
  into the generated header. They are replaced by the real (unverified) import
  functions once those are written.\<close>

definition parse_inputs :: \<open>c_inputs ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>parse_inputs \<equiv> \<lambda>a. Mreturn 0\<close>
definition parse_proof :: \<open>c_proof ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>parse_proof \<equiv> \<lambda>a. Mreturn 0\<close>
definition parse_target :: \<open>c_target ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>parse_target \<equiv> \<lambda>a. Mreturn 0\<close>

export_llvm
  parse_inputs is \<open>char parse_inputs(inputs*)\<close>
  parse_proof is \<open>char parse_proof(proof*)\<close>
  parse_target is \<open>char parse_target(polynomial*)\<close>
  defines \<open>
    typedef struct {char *ptr; uint64_t len;} slice;
    typedef struct {slice *vars_ptr; uint64_t num_vars;} term;
    typedef struct {slice coeff; struct {char neg; term vars;};} monomial;
    typedef struct {monomial *mnmls_ptr; uint64_t num_mnmls;} polynomial;
    typedef struct {uint64_t idx; polynomial poly;} input;
    typedef struct {input *inputs; uint64_t num_inputs;} inputs;
    typedef struct {polynomial *poly_ptr; uint64_t idx;} summand;
    typedef struct {uint64_t target_idx; struct {summand *summands; struct {uint64_t num_summands; polynomial res;};};} lc_rule;
    typedef struct {uint64_t idx; struct {slice var; polynomial poly;};} ext_rule;
    typedef struct {int32_t typ; union {lc_rule lc; uint64_t del; ext_rule ext;} u;} rule;
    typedef struct {rule *rules_ptr; uint64_t num_rules;} proof;
  \<close>
  file "/tmp/pasteque_interface.ll"


end
