theory LPAC_CodeExport
  imports
    LPAC_Efficient_Checker_Synthesis
    BigInt_String
begin

text \<open>This theory defines types for the c interface and also handles importing
  the data generated by the c parser into the target datatypes of the verified
  parser. Note that most functions in here are not verified, so they are part of the
  trusted code base.\<close>

section \<open>A ternary union type\<close>

text \<open>The library only ships the binary union example \<open>ll_sum\<close> (and not in the
  IICF import). The tagged union in \<open>rule\<close> has three members, so we provide a
  ternary union type, modelled on \<open>ll_sum\<close>.\<close>

declare [[llc_compile_union=true]]

datatype ('a,'b,'c) ll_union3 =
    is_U3Zero: U3Zero
  | is_U3a: U3a (the_u3a: 'a)
  | is_U3b: U3b (the_u3b: 'b)
  | is_U3c: U3c (the_u3c: 'c)

instantiation ll_union3 :: (llvm_rep,llvm_rep,llvm_rep) llvm_rep
begin
  fun to_val_ll_union3 :: \<open>('a,'b,'c) ll_union3 \<Rightarrow> llvm_val\<close> where
    "to_val_ll_union3 U3Zero = LL_UNION (UN_ZERO_INIT [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3a x) = LL_UNION (UN_SEL [] (to_val x) [struct_of TYPE('b), struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3b x) = LL_UNION (UN_SEL [struct_of TYPE('a)] (to_val x) [struct_of TYPE('c)])"
  | "to_val_ll_union3 (U3c x) = LL_UNION (UN_SEL [struct_of TYPE('a), struct_of TYPE('b)] (to_val x) [])"

  fun from_val_ll_union3 :: \<open>llvm_val \<Rightarrow> ('a,'b,'c) ll_union3\<close> where
    "from_val_ll_union3 (LL_UNION (UN_ZERO_INIT _)) = U3Zero"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [] x [_,_])) = U3a (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_] x [_])) = U3b (from_val x)"
  | "from_val_ll_union3 (LL_UNION (UN_SEL [_,_] x [])) = U3c (from_val x)"
  | "from_val_ll_union3 _ = undefined"

  definition [simp]: "struct_of_ll_union3 (_::('a,'b,'c) ll_union3 itself) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  definition [simp]: "init_ll_union3 = U3Zero"

  instance
    apply standard
    apply (all \<open>(clarsimp simp: comp_def fun_eq_iff)?\<close>)
    subgoal for x by (cases x) auto
    subgoal for v by (cases v rule: from_val_ll_union3.cases) auto
    subgoal for x by (cases x) auto
    done
end

lemma struct_of_ll_union3[ll_struct_of]:
  "struct_of TYPE(('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3) = VS_UNION [struct_of TYPE('a), struct_of TYPE('b), struct_of TYPE('c)]"
  by simp

definition ll_u3_extr_a :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'a llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_a x \<equiv> ll_dest_union x 0\<close>

definition ll_u3_extr_b :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'b llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_b x \<equiv> ll_dest_union x 1\<close>

definition ll_u3_extr_c :: \<open>('a::llvm_rep,'b::llvm_rep,'c::llvm_rep) ll_union3 \<Rightarrow> 'c llM\<close> where
  [llvm_code,llvm_inline]: \<open>ll_u3_extr_c x \<equiv> ll_dest_union x 2\<close>

lemma ll_u3_extr_simps:
  \<open>is_U3a x \<Longrightarrow> ll_u3_extr_a x = Mreturn (the_u3a x)\<close>
  \<open>is_U3b x \<Longrightarrow> ll_u3_extr_b x = Mreturn (the_u3b x)\<close>
  \<open>is_U3c x \<Longrightarrow> ll_u3_extr_c x = Mreturn (the_u3c x)\<close>
  unfolding ll_u3_extr_a_def ll_u3_extr_b_def ll_u3_extr_c_def
  by (cases x; simp add: ll_dest_union_def checked_from_val_def llvm_dest_union_def)+

lemma ll_u3_extr_rules[vcg_rules]:
  \<open>llvm_htriple (\<up>(is_U3a x)) (ll_u3_extr_a x) (\<lambda>r. \<up>(r = the_u3a x))\<close>
  \<open>llvm_htriple (\<up>(is_U3b x)) (ll_u3_extr_b x) (\<lambda>r. \<up>(r = the_u3b x))\<close>
  \<open>llvm_htriple (\<up>(is_U3c x)) (ll_u3_extr_c x) (\<lambda>r. \<up>(r = the_u3c x))\<close>
  supply [vcg_normalize_simps] = ll_u3_extr_simps
  by vcg

section \<open>C Interface Types\<close>

text \<open>We describe the datatypes that will be instanciated by the c parser.\<close>

type_synonym c_slice = \<open>64 word \<times> 8 word ptr\<close>
type_synonym c_term = \<open>64 word \<times> c_slice ptr\<close>
type_synonym c_monomial = \<open>c_slice \<times> 8 word \<times> c_term\<close>
type_synonym c_polynomial = \<open>64 word \<times> c_monomial ptr\<close>

type_synonym c_input = \<open>64 word \<times> c_polynomial\<close>
type_synonym c_inputs = \<open>64 word \<times> c_input ptr\<close>

type_synonym c_summand = \<open>c_polynomial ptr \<times> 64 word\<close>
type_synonym c_summands = \<open>64 word \<times> c_summand ptr\<close>
type_synonym c_lc_rule = \<open>64 word \<times> c_summands \<times> c_polynomial\<close>
type_synonym c_del_rule = \<open>64 word\<close>
type_synonym c_ext_rule = \<open>64 word \<times> c_slice \<times> c_polynomial\<close>
type_synonym c_rule = \<open>32 word \<times> (c_lc_rule, c_del_rule, c_ext_rule) ll_union3\<close>
type_synonym c_proof = \<open>64 word \<times> c_rule ptr\<close>

type_synonym c_target = \<open>c_polynomial\<close>

section \<open>Import functions\<close>

subsection \<open>Generic Array to Open List Conversion\<close>

text \<open>We use lists to represent strings (and thus variables) and polynomials.
  From the c-parser, they are given as arrays, so we need conversion functions.
  On the HOL level, these functions are essentially trivial list-copy implementations.
  The important point is that on the array side, they use the `ith` operation while on
  list side we use cons (which we have implemented for open lists and owning lists...)
\<close>

text \<open>We define a synonym for `id` to indicate Array to list conversion on the HOL level.
  Similarly to how we can use `COPY` on the HOL side to enforce copying of structures.\<close>
definition \<open>ARR2LS = (id :: 'a list \<Rightarrow> 'a list)\<close>

lemma arr2ls_refine: \<open>(\<lambda>x. RETURN x, RETURN o ARR2LS) \<in> Id \<rightarrow>\<^sub>f \<langle>Id\<rangle>nres_rel\<close>
  apply (intro frefI nres_relI)
  unfolding ARR2LS_def
  by auto

definition arr_to_list :: \<open>'a list \<Rightarrow> 'a list nres\<close> where
  \<open>arr_to_list arr = doN{
    ASSERT(length arr < max_snat 64);
    let l = length arr;
    (ls, _) \<leftarrow> WHILEIT
      (\<lambda>(ls, i). i \<le> length arr \<and> ls = drop (l-i) arr)
      (\<lambda>(_, i). i < length arr)
      (\<lambda>(ls, i). doN {
        ASSERT(i < length arr);
        RETURN(arr!(l-i-1) # ls, i+1)
      })
      ([], 0);
    RETURN ls
  }\<close>

lemma arr_to_list_correct:
    shows \<open>(arr_to_list, \<lambda>x. RETURN x) \<in> [\<lambda> arr. length arr < max_snat 64]\<^sub>f Id \<rightarrow> \<langle>Id\<rangle>nres_rel\<close>
  apply (intro frefI nres_relI)
  subgoal for x y
    unfolding arr_to_list_def
    apply (refine_vcg WHILEIT_rule[where R="measure (\<lambda>(_, i). length x - i)"])
    apply clarsimp_all
    subgoal by (metis drop_minus rev_nth)
    subgoal by linarith
    done
  done

lemmas arr_to_list_refine = arr_to_list_correct[FCOMP arr2ls_refine]

context
  fixes A :: \<open>'a \<Rightarrow> 'b::llvm_rep \<Rightarrow> assn\<close>
    and Afree :: \<open>'b \<Rightarrow> unit llM\<close>
  assumes A_pure[safe_constraint_rules]: \<open>is_pure A\<close>
  assumes [sepref_frame_free_rules]: \<open>MK_FREE A Afree\<close>
begin

sepref_definition parr_to_list_impl is \<open>arr_to_list\<close>
  :: \<open>(larray_assn' size_t A)\<^sup>k \<rightarrow>\<^sub>a (os_assn A)\<close>
  unfolding arr_to_list_def
  apply (annot_snat_const size_t)
  by sepref

lemmas ARR2LS_hnr = 
  parr_to_list_impl.refine[FCOMP arr_to_list_refine]

end

subsection \<open>Primitive importers\<close>

text \<open>Here we now use our array \<rightarrow> list conversion to import slices into strings/big numbers.
  We do some trickery to get high level HOL functions here, so we can potentially verify
  correctness at some point without having to resort to low-level vcg proofs.\<close>

definition slice_to_str :: \<open>char list \<Rightarrow> char list\<close>
  where \<open>slice_to_str \<equiv> ARR2LS\<close>

abbreviation \<open>stra_assn \<equiv> larray_assn' size_t char_assn\<close>
lemmas stra_ARR2LS_hnr = ARR2LS_hnr[OF char_assn_pure]

lemmas parr_to_list_impl_char_code [llvm_inline] =
  parr_to_list_impl_def[OF char_assn_pure mk_free_is_pure[OF char_assn_pure]]

text \<open>Note that `c_slice = \<open>64 word \<times> 8 word ptr\<close>`, i.e. `c_slice` is a list of characters.
  In particular, `c_slice` is a refinment target given by `stra_assn`.\<close>
sepref_def slice_to_str_impl is \<open>RETURN o slice_to_str\<close>
  :: \<open>stra_assn\<^sup>k \<rightarrow>\<^sub>a strl_assn\<close>
  unfolding slice_to_str_def 
  supply [sepref_fr_rules] = stra_ARR2LS_hnr
  by sepref

definition slice_to_big_int :: \<open>8 word list \<Rightarrow> int nres\<close> where
  \<open>slice_to_big_int s \<equiv> if length s = 0 then RETURN 0 else str_to_int s\<close>

(* TODO: fix string parsing for `char list` on high level - then we don't
 * have to do `word_assn` vs `char_assn` gymnastics anymore *)
abbreviation \<open>strac_assn \<equiv> larray_assn' size_t (word_assn' TYPE(8))\<close>

sepref_register \<open>str_to_int\<close>
sepref_def slice_to_big_int_impl is \<open>slice_to_big_int\<close>
  :: \<open>strac_assn\<^sup>k \<rightarrow>\<^sub>a sbi_assn\<close>
  unfolding slice_to_big_int_def 
  apply (annot_snat_const size_t)
  by sepref

section \<open>Exported C header\<close>

section \<open>Importing the C-Parsed Structures\<close>

subsection \<open>Concrete Type Abbreviations\<close>

type_synonym sbi_conc = \<open>sbin_conc \<times> 1 word\<close>
type_synonym mnml_conc = \<open>monom_conc \<times> sbi_conc\<close>
type_synonym poly_conc = \<open>mnml_conc os_list\<close>
type_synonym strl_conc = \<open>8 word os_list\<close>
type_synonym step_conc = \<open>(poly_conc, strl_conc) pac_step_impl\<close>

subsection \<open>Leaf Imports\<close>

definition imp_term :: \<open>c_term \<Rightarrow> monom_conc llM\<close> where[llvm_code]:
  \<open>imp_term \<equiv> \<lambda>(lt, slp). doM {
    tsls \<leftarrow> os_empty;
    (tsls, _) \<leftarrow> llc_while
      (\<lambda>(tsls, i). ll_cmp (i \<noteq> 0))
      (\<lambda>(tsls, i). doM {
        i \<leftarrow> ll_sub i (signed_nat 1);
        s \<leftarrow> array_nth slp i;
        si \<leftarrow> slice_to_str_impl s;
        tsls \<leftarrow> os_prepend si tsls;
        Mreturn (tsls, i)
      }) (tsls, lt);
    Mreturn tsls
  }\<close>

definition imp_coeff :: \<open>(c_slice \<times> 8 word) \<Rightarrow> sbi_conc llM\<close> where[llvm_code]:
  \<open>imp_coeff \<equiv> \<lambda>(sl, sgn). doM {
    sbi \<leftarrow> slice_to_big_int_impl sl;
    if sgn = 1 then doM {
      sbi \<leftarrow> sbi_inv_impl sbi;
      Mreturn sbi
    }
    else
      Mreturn sbi
  }\<close>

definition imp_monomial :: \<open>c_monomial \<Rightarrow> mnml_conc llM\<close> where[llvm_code]:
  \<open>imp_monomial \<equiv> \<lambda>(sl, sgn, t). doM {
    c \<leftarrow> imp_coeff (sl, sgn);
    n \<leftarrow> imp_term t;
    Mreturn (n, c)
  }\<close>

definition imp_poly :: \<open>c_polynomial \<Rightarrow> poly_conc llM\<close> where [llvm_code]:
  \<open>imp_poly \<equiv> \<lambda>(n, a). doM {
     (p, _) \<leftarrow> llc_while
       (\<lambda>(p, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(p, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          mo \<leftarrow> array_nth a i;
          m \<leftarrow> imp_monomial mo;
          p \<leftarrow> os_prepend m p;
          Mreturn (p, i)
        }) (null, n);
     Mreturn p
   }\<close>

definition imp_inputs :: \<open>c_inputs \<Rightarrow> (64 word \<times> poly_conc) os_list llM\<close> where [llvm_code]:
  \<open>imp_inputs \<equiv> \<lambda>(n, a). doM {
     (xs, _) \<leftarrow> llc_while
       (\<lambda>(xs, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(xs, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          inp \<leftarrow> array_nth a i;
          case inp of (idx, pc) \<Rightarrow> doM {
            p \<leftarrow> imp_poly pc;
            xs \<leftarrow> os_prepend (idx, p) xs;
            Mreturn (xs, i)
          }
        }) (null, n);
     Mreturn xs
   }\<close>

definition imp_srcs :: \<open>c_summands \<Rightarrow> (poly_conc \<times> 64 word) os_list llM\<close>
  where [llvm_code]:
  \<open>imp_srcs \<equiv> \<lambda>(n, a). doM {
     (xs, _) \<leftarrow> llc_while
       (\<lambda>(xs, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(xs, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          smd \<leftarrow> array_nth a i;
          case smd of (pp, idx) \<Rightarrow> doM {
            q \<leftarrow> if pp = null then poly_one_impl
                else doM { pc \<leftarrow> ll_load pp; imp_poly pc };
            xs \<leftarrow> os_prepend (q, idx) xs;
            Mreturn (xs, i)
          }
        }) (null, n);
     Mreturn xs
   }\<close>

definition imp_step :: \<open>c_rule \<Rightarrow> step_conc llM\<close> where [llvm_code]:
  \<open>imp_step \<equiv> \<lambda>(t, u). doM {
     if t = 0 then doM {          \<comment> \<open>S_LINCOM\<close>
       lc \<leftarrow> ll_u3_extr_a u;
       case lc of (tidx, smds, res) \<Rightarrow> doM {
         srcs \<leftarrow> imp_srcs smds;
         r \<leftarrow> imp_poly res;
         CL_impl srcs tidx r
       }
     } else if t = 1 then doM {   \<comment> \<open>S_DEL\<close>
       idx \<leftarrow> ll_u3_extr_b u;
       Del_impl idx
     } else doM {                 \<comment> \<open>S_EXT\<close>
       er \<leftarrow> ll_u3_extr_c u;
       case er of (idx, vsl, resp) \<Rightarrow> doM {
         v \<leftarrow> slice_to_str_impl vsl;
         r \<leftarrow> imp_poly resp;
         Extension_impl idx v r
       }
     }
   }\<close>

definition imp_proof :: \<open>c_proof \<Rightarrow> step_conc os_list llM\<close> where [llvm_code]:
  \<open>imp_proof \<equiv> \<lambda>(n, a). doM {
     (xs, _) \<leftarrow> llc_while
       (\<lambda>(xs, i). ll_cmp (i \<noteq> 0))
       (\<lambda>(xs, i). doM {
          i \<leftarrow> ll_sub i (signed_nat 1);
          r \<leftarrow> array_nth a i;
          st \<leftarrow> imp_step r;
          xs \<leftarrow> os_prepend st xs;
          Mreturn (xs, i)
        }) (null, n);
     Mreturn xs
   }\<close>

abbreviation imp_target :: \<open>c_target \<Rightarrow> poly_conc llM\<close> where
  \<open>imp_target \<equiv> imp_poly\<close>

text \<open>"Non-Efficient" Checker\<close>

definition run_checker :: \<open>c_inputs ptr \<Rightarrow> c_proof ptr \<Rightarrow> c_target ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>run_checker \<equiv> \<lambda> cinpsp cprfp ctgtp. doM {
    cinps \<leftarrow> ll_load cinpsp;
    cprf \<leftarrow> ll_load cprfp;
    ctgt \<leftarrow> ll_load ctgtp;
    isainps \<leftarrow> imp_inputs cinps; 
    isaprf \<leftarrow> imp_proof cprf;
    isatgt \<leftarrow> imp_target ctgt;
    ((st, res), vs, p) \<leftarrow> full_checker_l3_impl isatgt isainps isaprf;
    Mreturn st 
  }\<close>

export_llvm
  run_checker is \<open>char run_checker(inputs*, proof*, polynomial*)\<close>
  defines \<open>
    typedef struct {uint64_t len; char *ptr;} slice;
    typedef struct {uint64_t num_vars; slice *vars_ptr;} term;
    typedef struct {slice coeff; struct {char neg; term vars;};} monomial;
    typedef struct {uint64_t num_mnmls; monomial *mnmls_ptr;} polynomial;
    typedef struct {uint64_t idx; polynomial poly;} input;
    typedef struct {uint64_t num_inputs; input *inputs;} inputs;
    typedef struct {polynomial *poly_ptr; uint64_t idx;} summand;
    typedef struct {uint64_t num_summands; summand *summands_ptr;} summands;
    typedef struct {uint64_t target_idx; struct {summands summands; polynomial res;};} lc_rule;
    typedef struct {uint64_t idx; struct {slice var; polynomial poly;};} ext_rule;
    typedef struct {int32_t typ; union {lc_rule lc; uint64_t del; ext_rule ext;} u;} rule;
    typedef struct {uint64_t num_rules; rule *rules_ptr;} proof;
  \<close>
  file "./code/pasteque.ll"

text \<open>Efficient Checker\<close>

definition run_shared_checker :: \<open>c_inputs ptr \<Rightarrow> c_proof ptr \<Rightarrow> c_target ptr \<Rightarrow> 8 word llM\<close> where[llvm_code]:
  \<open>run_shared_checker \<equiv> \<lambda> cinpsp cprfp ctgtp. doM {
    cinps \<leftarrow> ll_load cinpsp;
    cprf \<leftarrow> ll_load cprfp;
    ctgt \<leftarrow> ll_load ctgtp;
    isainps \<leftarrow> imp_inputs cinps; 
    isaprf \<leftarrow> imp_proof cprf;
    isatgt \<leftarrow> imp_target ctgt;
    ((st, res), vs, p) \<leftarrow> full_checker_l_s3_impl isatgt isainps isaprf;
    Mreturn st 
  }\<close>

export_llvm
  run_checker is \<open>char run_shared_checker(inputs*, proof*, polynomial*)\<close>
  defines \<open>
    typedef struct {uint64_t len; char *ptr;} slice;
    typedef struct {uint64_t num_vars; slice *vars_ptr;} term;
    typedef struct {slice coeff; struct {char neg; term vars;};} monomial;
    typedef struct {uint64_t num_mnmls; monomial *mnmls_ptr;} polynomial;
    typedef struct {uint64_t idx; polynomial poly;} input;
    typedef struct {uint64_t num_inputs; input *inputs;} inputs;
    typedef struct {polynomial *poly_ptr; uint64_t idx;} summand;
    typedef struct {uint64_t num_summands; summand *summands_ptr;} summands;
    typedef struct {uint64_t target_idx; struct {summands summands; polynomial res;};} lc_rule;
    typedef struct {uint64_t idx; struct {slice var; polynomial poly;};} ext_rule;
    typedef struct {int32_t typ; union {lc_rule lc; uint64_t del; ext_rule ext;} u;} rule;
    typedef struct {uint64_t num_rules; rule *rules_ptr;} proof;
  \<close>
  file "./code/pasteque_shared.ll"

end
