// Generated by Isabelle-LLVM. Do not modify.
#ifndef _PASTEQUE_H
#define _PASTEQUE_H 1


#include <stdint.h>


typedef struct polynomial polynomial;
typedef struct slice slice;
typedef struct ext_rule ext_rule;
typedef struct summands summands;
typedef struct lc_rule lc_rule;
typedef struct rule rule;
typedef struct term term;
typedef struct input input;
typedef struct proof proof;
typedef struct inputs inputs;
typedef struct summand summand;
typedef struct monomial monomial;

typedef struct polynomial {
  uint64_t num_mnmls;
  monomial*mnmls_ptr;
} polynomial;
typedef struct slice {
  uint64_t len;
  char*ptr;
} slice;
typedef struct ext_rule {
  uint64_t idx;
  struct {
    slice var;
    polynomial poly;
  };
} ext_rule;
typedef struct summands {
  uint64_t num_summands;
  summand*summands_ptr;
} summands;
typedef struct lc_rule {
  uint64_t target_idx;
  struct {
    summands summands;
    polynomial res;
  };
} lc_rule;
typedef struct rule {
  int32_t typ;
  union {
    lc_rule lc;
    uint64_t del;
    ext_rule ext;
  }u;
} rule;
typedef struct term {
  uint64_t num_vars;
  slice*vars_ptr;
} term;
typedef struct input {
  uint64_t idx;
  polynomial poly;
} input;
typedef struct proof {
  uint64_t num_rules;
  rule*rules_ptr;
} proof;
typedef struct inputs {
  uint64_t num_inputs;
  input*inputs;
} inputs;
typedef struct summand {
  polynomial*poly_ptr;
  uint64_t idx;
} summand;
typedef struct monomial {
  slice coeff;
  struct {
    char neg;
    term vars;
  };
} monomial;

char run_checker(inputs*, proof*, polynomial*);

#endif
