/* parser.h — public interface of the trusted C tokenizer/parser (parser.c).
 *
 * The parsed data structures are the Isabelle-facing ABI types generated by the
 * Isabelle-LLVM code generator (pasteque.h): length-carrying arrays are ordered
 * length-first, so a parsed `inputs`/`proof`/`polynomial` is bit-compatible with
 * the verified import functions and can be handed to them without any glue.
 */
#ifndef PARSER_H
#define PARSER_H

#include <stddef.h>
#include <stdint.h>

/* The verified checker comes in two flavours, each exported to its own ABI
 * header by LPAC_CodeExport.thy. Both headers declare the *same* data-structure
 * types but a differently-named entry point, and each ships its own copy of the
 * import functions — so exactly one may be compiled/linked at a time. Define
 * PASTEQUE_SHARED (e.g. `-DPASTEQUE_SHARED`, or `make pasteque_shared`) to build
 * against the shared-variables checker; otherwise the plain checker is used. */
#ifdef PASTEQUE_SHARED
#include "pasteque_shared.h" /* run_shared_checker + the ABI types */
#define RUN_CHECKER run_shared_checker
#else
#include "pasteque.h" /* run_checker + slice, term, monomial, polynomial,
                          input, inputs, summand, summands, lc_rule, ext_rule,
                          rule, proof */
#define RUN_CHECKER run_checker
#endif

/* -- rule tags (pasteque.h stores the tag as a bare int32_t) ----------------- */
typedef enum {
  S_LINCOM = 0,
  S_DEL,
  S_EXT,
} rule_type;

/* target ::= poly ';' — c_target collapses to a bare polynomial on the Isabelle
 * side, so there is no `target` struct in pasteque.h; we keep a thin wrapper. */
typedef struct {
  polynomial poly;
} target;

/* -- Arena allocator (opaque blocks) ----------------------------------------- */
typedef struct arena_block arena_block;
typedef struct {
  arena_block *head;
} arena;

void arena_free(arena *a);

/* -- Tokens (opaque to callers: produced by lex_file, consumed by parse_*) ---- */
typedef struct token token;
typedef struct {
  const token *data;
  size_t len;
} token_array;

/* Read a file and tokenize it. On success the caller owns both *buf_out (the
 * text the token slices point into) and ta_out->data. Returns 0 on success. */
int lex_file(const char *path, char **buf_out, token_array *ta_out);

/* Parsers. Each allocates its whole result tree in the arena `a`. */
inputs parse_inputs(arena *a, const token_array *ta);
proof parse_proof(arena *a, const token_array *ta);
target parse_target(arena *a, const token_array *ta);

/* Debug dumps: reproduce the input syntax (so parsing can be checked by diff). */
void dump_polynomial(const polynomial *p);
void dump_rule(const rule *r);

#endif /* PARSER_H */
