// Generated by Isabelle-LLVM. Do not modify.
#ifndef _TERM_H
#define _TERM_H 1


#include <stdint.h>


typedef struct stra stra;
typedef struct strnode strnode;
typedef struct charnode charnode;
typedef struct strl_builder strl_builder;
typedef struct term_builder term_builder;

typedef struct stra {
  int64_t len;
  char*ptr;
} stra;
typedef struct strnode {
  stra s;
  strnode*next;
} strnode;
typedef struct charnode {
  char c;
  charnode*next;
} charnode;
typedef struct strl_builder {
  charnode*head;
  charnode*tail;
} strl_builder;
typedef struct term_builder {
  strnode*head;
  strnode*tail;
} term_builder;

charnode* strl_emp();
strnode* term_emp();
void strl_append(strl_builder*, char);
charnode* strl_finish(strl_builder*);
void term_append(term_builder*, int64_t, char*);
strnode* term_finish(term_builder*);
strl_builder* strl_builder_new();
term_builder* term_builder_new();

#endif
